"""
Trading strategies for Polymarket.

Strategy 1 — Momentum + Order-Book Imbalance
─────────────────────────────────────────────
Combines 24-h price momentum with order-book bid/ask imbalance.
Signal weights, thresholds, and adjustments are all dynamic — the
AdaptiveLearner can tune them online based on trade outcomes.

Strategy 2 — Latency Arbitrage (BTC / crypto contracts)
───────────────────────────────────────────────────────
Polymarket updates crypto-outcome contract prices slower than real-time
exchange feeds.  This strategy:
  1. Pulls the live BTC (or other asset) price from external feeds.
  2. Compares it to the implied price in the Polymarket contract.
  3. When the lag exceeds a configurable threshold it places a rapid
     limit order to capture the mispricing before the market catches up.
"""
from __future__ import annotations

import time
from dataclasses import dataclass
from typing import TYPE_CHECKING

import numpy as np
import requests
from loguru import logger

from src.client import Market, OrderBook, PricePoint
import config

if TYPE_CHECKING:
    from src.learner import StrategyParams

# ---------------------------------------------------------------------------
# Defaults (used when no adaptive params are provided)
# ---------------------------------------------------------------------------

DEFAULT_SIGNAL_THRESHOLD = 0.15
DEFAULT_MAX_SIGNAL_ADJUST = 0.07
DEFAULT_MOMENTUM_WEIGHT = 0.50
DEFAULT_IMBALANCE_WEIGHT = 0.50
OB_LEVELS = 10
MOMENTUM_NORMALISER = 0.20


# ---------------------------------------------------------------------------
# Output dataclass
# ---------------------------------------------------------------------------

@dataclass
class TradeSignal:
    market_id: str
    question: str
    side: str            # "YES" | "NO"
    token_id: str
    market_price: float  # current market mid price for the chosen token
    fair_value: float    # our estimated fair price
    edge: float          # fair_value - market_price (positive = we have edge)
    signal: float        # composite signal [-1, 1]
    confidence: str      # "LOW" | "MEDIUM" | "HIGH"
    # Sub-signals (used by learner to attribute wins/losses)
    momentum_signal: float  = 0.0
    imbalance_signal: float = 0.0
    # Latency arb fields
    is_latency_arb: bool = False
    lag_pct: float = 0.0
    # Time urgency (hours until market closes; None = unknown)
    hours_to_close: float | None = None
    # Best ask at signal time — used for aggressive fills on ultra-short markets
    best_ask: float | None = None
    # Set True for trades generated by NewsArbitrageStrategy — routed to news learner
    is_news_arb: bool = False

    def __str__(self) -> str:
        tag = "[LATENCY-ARB] " if self.is_latency_arb else ""
        return (
            f"{tag}[{self.confidence}] {self.side} {self.question[:60]} | "
            f"mkt={self.market_price:.3f}  fv={self.fair_value:.3f}  "
            f"edge={self.edge:+.3f}  sig={self.signal:+.3f}"
        )


# ═══════════════════════════════════════════════════════════════════════════
# Strategy 1: Momentum + Imbalance
# ═══════════════════════════════════════════════════════════════════════════

class MomentumImbalanceStrategy:
    """
    Scans a single market and returns a TradeSignal if an opportunity is
    found.  All tuneable constants come from `params` (set by the learner).
    """

    def __init__(self, params: StrategyParams | None = None) -> None:
        self._params = params

    # -- properties for current param values (fallback to defaults) --------

    @property
    def _momentum_weight(self) -> float:
        return self._params.momentum_weight if self._params else DEFAULT_MOMENTUM_WEIGHT

    @property
    def _imbalance_weight(self) -> float:
        return self._params.imbalance_weight if self._params else DEFAULT_IMBALANCE_WEIGHT

    @property
    def _signal_threshold(self) -> float:
        return self._params.signal_threshold if self._params else DEFAULT_SIGNAL_THRESHOLD

    @property
    def _max_signal_adjust(self) -> float:
        return self._params.max_signal_adjust if self._params else DEFAULT_MAX_SIGNAL_ADJUST

    # -- analysis ----------------------------------------------------------

    def analyse(
        self,
        market: Market,
        order_book: OrderBook | None,
        price_history: list[PricePoint],
    ) -> TradeSignal | None:
        try:
            mom_sig = self._momentum_signal(market, price_history)
            imb_sig = self._imbalance_signal(order_book)

            composite = (
                self._momentum_weight * mom_sig
                + self._imbalance_weight * imb_sig
            )

            logger.debug(
                f"{market.question[:50]} | mom={mom_sig:+.3f}  "
                f"imb={imb_sig:+.3f}  comp={composite:+.3f}"
            )

            if abs(composite) < self._signal_threshold:
                return None

            # Choose direction
            if composite > 0:
                side = "YES"
                token = market.yes_token
                mid = order_book.mid if order_book else market.yes_price
            else:
                side = "NO"
                token = market.no_token
                mid = (1.0 - order_book.mid) if order_book else market.no_price
                composite = -composite  # flip for edge calc

            fair_value = mid * (1.0 + composite * self._max_signal_adjust)
            fair_value = float(np.clip(fair_value, 0.01, 0.99))
            edge = fair_value - mid

            if edge < config.MIN_EDGE:
                return None

            confidence = (
                "HIGH"   if composite > 0.5 else
                "MEDIUM" if composite > 0.3 else
                "LOW"
            )

            return TradeSignal(
                market_id=market.id,
                question=market.question,
                side=side,
                token_id=token.token_id,
                market_price=mid,
                fair_value=fair_value,
                edge=edge,
                signal=composite,
                confidence=confidence,
                momentum_signal=mom_sig,
                imbalance_signal=imb_sig,
            )

        except Exception as exc:
            logger.warning(f"Strategy error on market {market.id}: {exc}")
            return None

    # -- sub-signals -------------------------------------------------------

    def _momentum_signal(
        self, market: Market, price_history: list[PricePoint]
    ) -> float:
        if len(price_history) < 2:
            return 0.0
        recent = price_history[-1].price
        lookback = min(24, len(price_history) - 1)
        past = price_history[-1 - lookback].price
        if past <= 0:
            return 0.0
        change = (recent - past) / past
        return float(np.clip(change / MOMENTUM_NORMALISER, -1.0, 1.0))

    def _imbalance_signal(self, ob: OrderBook | None) -> float:
        if ob is None:
            return 0.0
        bid_qty = sum(float(b.get("size", 0)) for b in ob.bids[:OB_LEVELS])
        ask_qty = sum(float(a.get("size", 0)) for a in ob.asks[:OB_LEVELS])
        total = bid_qty + ask_qty
        if total == 0:
            return 0.0
        return float((bid_qty - ask_qty) / total)


# ═══════════════════════════════════════════════════════════════════════════
# Strategy 2: Latency Arbitrage
# ═══════════════════════════════════════════════════════════════════════════

# ── Price feeds ──────────────────────────────────────────────────────────────
# Binance is the fastest public feed; CoinGecko is fallback (rate-limited)
_BINANCE_FEEDS: dict[str, str] = {
    "BTC":  "https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT",
    "ETH":  "https://api.binance.com/api/v3/ticker/price?symbol=ETHUSDT",
    "XRP":  "https://api.binance.com/api/v3/ticker/price?symbol=XRPUSDT",
    "SOL":  "https://api.binance.com/api/v3/ticker/price?symbol=SOLUSDT",
    "DOGE": "https://api.binance.com/api/v3/ticker/price?symbol=DOGEUSDT",
}
_COINGECKO_IDS: dict[str, str] = {
    "BTC":  "bitcoin",
    "ETH":  "ethereum",
    "XRP":  "ripple",
    "SOL":  "solana",
    "DOGE": "dogecoin",
}

_PRICE_CACHE: dict[str, tuple[float, float]] = {}     # symbol → (price, timestamp)
_EXCHANGE_PRESSURE: dict[str, float] = {}            # symbol → bid/ask imbalance (-1..+1)
_CACHE_TTL = 2.0   # seconds

# Rolling 60-second price history for momentum: symbol → [(price, ts), ...]
_PRICE_HISTORY: dict[str, list[tuple[float, float]]] = {}
_HISTORY_WINDOW = 600  # keep 10 minutes of ticks for multi-timeframe analysis


def _fetch_price(symbol: str) -> float | None:
    """Fetch live price for any supported symbol (cached 2 s)."""
    sym = symbol.upper()
    cached = _PRICE_CACHE.get(sym)
    if cached and (time.time() - cached[1]) < _CACHE_TTL:
        return cached[0]

    price: float | None = None

    # Try Binance first (fastest, no rate limit for single ticker)
    if sym in _BINANCE_FEEDS:
        try:
            r = requests.get(_BINANCE_FEEDS[sym], timeout=3)
            r.raise_for_status()
            price = float(r.json()["price"])
        except Exception:
            pass

    # Fall back to CoinGecko
    if price is None and sym in _COINGECKO_IDS:
        try:
            cg_id = _COINGECKO_IDS[sym]
            r = requests.get(
                f"https://api.coingecko.com/api/v3/simple/price?ids={cg_id}&vs_currencies=usd",
                timeout=4,
            )
            r.raise_for_status()
            price = float(r.json()[cg_id]["usd"])
        except Exception:
            pass

    if price is not None:
        _PRICE_CACHE[sym] = (price, time.time())
        # Record in rolling history
        hist = _PRICE_HISTORY.setdefault(sym, [])
        now = time.time()
        hist.append((price, now))
        # Trim to window
        cutoff = now - _HISTORY_WINDOW
        _PRICE_HISTORY[sym] = [(p, t) for p, t in hist if t >= cutoff]

    return price


def _fetch_btc_price() -> float | None:
    """Backward-compatible wrapper."""
    return _fetch_price("BTC")


def _price_momentum(symbol: str, window_secs: int) -> float | None:
    """
    Returns the % price change over the last `window_secs` seconds.
    Positive = rising, negative = falling. None if insufficient history.
    """
    hist = _PRICE_HISTORY.get(symbol.upper(), [])
    now = time.time()
    window = [(p, t) for p, t in hist if now - t <= window_secs * 1.25]
    if len(window) < 2:
        return None
    oldest_price = window[0][0]
    newest_price = window[-1][0]
    if oldest_price <= 0:
        return None
    return (newest_price - oldest_price) / oldest_price


def _price_momentum_60s(symbol: str) -> float | None:
    return _price_momentum(symbol, 60)


def _price_momentum_30s(symbol: str) -> float | None:
    return _price_momentum(symbol, 30)


def _price_momentum_5m(symbol: str) -> float | None:
    return _price_momentum(symbol, 300)


def _price_acceleration(symbol: str) -> float | None:
    """
    Returns how much momentum is changing (2nd derivative of price).
    Positive = trend is speeding up, negative = trend is slowing/reversing.
    Computed as: mom_30s - mom_60s (scaled to same units).
    Returns None if insufficient data.
    """
    m30 = _price_momentum_30s(symbol)
    m60 = _price_momentum_60s(symbol)
    if m30 is None or m60 is None:
        return None
    # Annualise to same time scale: m30 is over 30s, m60 over 60s
    # Acceleration = recent 30s rate vs older 60s rate
    m30_scaled = m30 * 2.0   # scale 30s → 60s equivalent
    return m30_scaled - m60


def _exchange_pressure(symbol: str) -> float:
    """
    Returns Binance bid/ask size imbalance for `symbol`.
    Range: -1 (heavy ask pressure, likely falling) to +1 (heavy bid pressure, likely rising).
    0.0 if no data available.
    """
    return _EXCHANGE_PRESSURE.get(symbol.upper(), 0.0)


def _multitf_consensus(symbol: str) -> tuple[float, str]:
    """
    Combines 30s, 60s, 5m momentum + exchange pressure into a single
    directional score and confidence.

    Returns: (direction_score, confidence)
      direction_score: positive = UP, negative = DOWN, magnitude = strength
      confidence: "HIGH" | "MEDIUM" | "LOW" | "NONE" (insufficient data)
    """
    sym = symbol.upper()
    hist = _PRICE_HISTORY.get(sym, [])

    # Require at least 5 distinct ticks AND 90 seconds of real price history.
    # With fewer ticks, all three timeframes return the same value (same 1-2 points
    # fall in every window) — this looks like strong agreement but is just noise.
    if len(hist) < 5:
        return 0.0, "NONE"
    time_span = hist[-1][1] - hist[0][1]
    if time_span < 90:
        return 0.0, "NONE"

    m30 = _price_momentum_30s(sym)
    m60 = _price_momentum_60s(sym)
    m5m = _price_momentum_5m(sym)
    pressure = _exchange_pressure(sym)
    accel = _price_acceleration(sym)

    available = sum(x is not None for x in [m30, m60, m5m])
    if available < 2:
        return 0.0, "NONE"

    # Reject signals where all available timeframes are identical — that means
    # only one distinct price exists in the history window (still warming up).
    vals = [x for x in [m30, m60, m5m] if x is not None]
    if len(vals) >= 2 and len(set(round(v, 8) for v in vals)) == 1:
        return 0.0, "NONE"

    signals = []
    if m30 is not None:
        signals.append(m30 * 2.0)     # 30s scaled to 60s units, weight 1.0×
    if m60 is not None:
        signals.append(m60 * 1.0)     # 60s baseline, weight 1.0×
    if m5m is not None:
        signals.append(m5m * 0.2)     # 5m smoothed, weight 0.2× (directional only)
    if pressure != 0.0:
        signals.append(pressure * 0.003)  # convert to % units

    consensus = sum(signals) / len(signals)

    # Check cross-timeframe agreement — all pointing same direction = higher confidence
    directions = []
    if m30 is not None:
        directions.append(1 if m30 > 0 else -1)
    if m60 is not None:
        directions.append(1 if m60 > 0 else -1)
    if m5m is not None:
        directions.append(1 if m5m > 0 else -1)
    if pressure != 0.0:
        directions.append(1 if pressure > 0.1 else (-1 if pressure < -0.1 else 0))

    n_agree = sum(d == (1 if consensus > 0 else -1) for d in directions if d != 0)
    n_total = sum(d != 0 for d in directions)
    agreement_ratio = n_agree / n_total if n_total > 0 else 0.5

    # Acceleration bonus: trend speeding up = more conviction
    accel_bonus = 0.0
    if accel is not None and (accel > 0) == (consensus > 0):
        accel_bonus = min(abs(accel) * 0.3, 0.002)

    strength = abs(consensus) + accel_bonus

    if agreement_ratio >= 0.75 and strength >= 0.004:
        conf = "HIGH"
    elif agreement_ratio >= 0.60 and strength >= 0.003:
        conf = "MEDIUM"
    elif agreement_ratio >= 0.50 and strength >= 0.002:
        conf = "LOW"
    else:
        conf = "NONE"

    return consensus, conf


# Keyword patterns that indicate BTC price-level contracts
_BTC_KEYWORDS = [
    "bitcoin", "btc", "btc/usd", "bitcoin price",
]


def _extract_btc_target(question: str) -> float | None:
    """
    Try to extract the dollar target from a market question like:
      "Will Bitcoin be above $70,000 on June 30?"
      "Will Bitcoin hit $100k by year end?"
      "Will Bitcoin reach $1m before GTA VI?"
    Returns the dollar figure or None.
    """
    q = question.lower()
    if not any(kw in q for kw in _BTC_KEYWORDS):
        return None

    import re
    # Match $70,000 / $70k / $1m / $1.5b with optional suffix k/m/b
    m = re.search(r"\$\s*([\d,]+(?:\.\d+)?)\s*([kmb])(?:\b|$)", q)
    if m:
        try:
            val = float(m.group(1).replace(",", ""))
            suffix = m.group(2)
            if suffix == "k":
                val *= 1_000
            elif suffix == "m":
                val *= 1_000_000
            elif suffix == "b":
                val *= 1_000_000_000
            return val
        except ValueError:
            pass

    # Fall back: plain number like $70,000 or $70000
    m = re.search(r"\$([\d,]+(?:\.\d+)?)", q)
    if not m:
        return None
    try:
        val = float(m.group(1).replace(",", ""))
        # Numbers under 500 are probably written as "70" meaning 70k
        if val < 500:
            val *= 1000
        return val
    except ValueError:
        return None


class LatencyArbStrategy:
    """
    Detects when Polymarket crypto contracts lag behind real-time price feeds
    and generates a signal to exploit the mispricing.

    Parameters:
        min_lag_pct – minimum % divergence to act on (default 0.3 %)
    """

    def __init__(self, min_lag_pct: float = 0.003) -> None:
        self.min_lag_pct = min_lag_pct

    def analyse(self, market: Market, order_book: OrderBook | None) -> TradeSignal | None:
        target = _extract_btc_target(market.question)
        if target is None:
            return None  # not a BTC price market

        live_price = _fetch_btc_price()
        if live_price is None:
            return None

        # Safety: skip markets where the live price is more than 30% away from
        # the target — those are long-dated prediction markets (e.g. "Will BTC
        # hit $1M?"), not genuine latency-arb opportunities.
        distance_pct = abs(live_price - target) / target
        if distance_pct > 0.30:
            logger.debug(
                f"[LATENCY-ARB] Skipping {market.question[:50]} — "
                f"BTC ${live_price:,.0f} is {distance_pct:.0%} away from "
                f"target ${target:,.0f} (threshold 30%)"
            )
            return None

        # Implied probability: how likely is BTC to be above $target?
        # Simple model: if live BTC is far above target → probability ≈ 1,
        # if far below → ≈ 0, linear in the band ±10 % around target.
        band = target * 0.10
        implied_prob = float(np.clip((live_price - target + band) / (2 * band), 0.01, 0.99))

        # Market probability
        mkt_yes = order_book.mid if order_book else market.yes_price

        lag = implied_prob - mkt_yes          # positive → market is too low → buy YES
        lag_pct = abs(lag)

        if lag_pct < self.min_lag_pct:
            return None

        if lag > 0:
            side = "YES"
            token = market.yes_token
            mkt_price = mkt_yes
        else:
            side = "NO"
            token = market.no_token
            mkt_price = 1.0 - mkt_yes

        fair_value = float(np.clip(implied_prob if side == "YES" else 1.0 - implied_prob, 0.01, 0.99))
        edge = fair_value - mkt_price

        if edge < config.MIN_EDGE:
            return None

        confidence = (
            "HIGH"   if lag_pct > 0.01 else
            "MEDIUM" if lag_pct > 0.005 else
            "LOW"
        )

        logger.info(
            f"[LATENCY-ARB] BTC live=${live_price:,.0f}  target=${target:,.0f}  "
            f"implied={implied_prob:.3f}  mkt={mkt_yes:.3f}  lag={lag:+.4f} "
            f"→ {side}"
        )

        return TradeSignal(
            market_id=market.id,
            question=market.question,
            side=side,
            token_id=token.token_id,
            market_price=mkt_price,
            fair_value=fair_value,
            edge=edge,
            signal=lag_pct,
            confidence=confidence,
            momentum_signal=0.0,
            imbalance_signal=0.0,
            is_latency_arb=True,
            lag_pct=lag_pct,
        )


# ═══════════════════════════════════════════════════════════════════════════
# Strategy 3: Up/Down 5-Minute Momentum
# ═══════════════════════════════════════════════════════════════════════════

import re as _re

# Maps keywords in the market question to the Binance symbol to fetch
_UPDOWN_ASSETS = {
    "xrp":      "XRP",
    "ripple":   "XRP",
    "btc":      "BTC",
    "bitcoin":  "BTC",
    "eth":      "ETH",
    "ethereum": "ETH",
    "sol":      "SOL",
    "solana":   "SOL",
    "doge":     "DOGE",
    "dogecoin": "DOGE",
    "bnb":      "BNB",
    "hype":     "HYPE",
}

# Minimum absolute 60s momentum to act on (0.05% move in 60s)
_MIN_MOMENTUM_PCT = 0.0005


def _detect_updown_market(question: str) -> str | None:
    """
    Returns the asset symbol if the question is an Up/Down short-interval
    crypto market.  Handles all Polymarket question phrasings:
      • "XRP Up or Down - March 3, 12:00PM-12:05PM ET"
      • "Will BTC be higher or lower in 15 minutes?"
      • "Bitcoin higher or lower in the next 5 min?"
      • "BTC up/down 15m"
    Returns None otherwise.
    """
    q = question.lower()
    # Must contain a directional phrase
    direction_phrases = (
        "up or down", "up/down", "higher or lower",
        "higher in", "lower in", "go up", "go down",
        "be up", "be down",
    )
    # Must also reference a short time interval to avoid false positives
    # on long-term questions like "Will BTC be higher by end of year?"
    time_phrases = (
        "5 min", "5min", "15 min", "15min", "5-min", "15-min",
        "5 minute", "15 minute", "next 5", "next 15",
        "in 5", "in 15", ":00pm", ":05pm", ":10pm", ":15pm",
        ":20pm", ":25pm", ":30pm", ":35pm", ":40pm", ":45pm",
        ":50pm", ":55pm", ":00am", ":05am", ":10am", ":15am",
    )
    has_direction = any(p in q for p in direction_phrases)
    has_time      = any(p in q for p in time_phrases)
    # "up or down" alone is strong enough (e.g. "XRP Up or Down - 12:00PM-12:05PM")
    if not has_direction:
        return None
    # For "higher or lower" we require a time phrase to avoid false positives
    if "higher or lower" in q and not has_time:
        return None
    for kw, sym in _UPDOWN_ASSETS.items():
        if kw in q:
            return sym
    return None


def _updown_window_mins(question: str) -> int | None:
    """
    Extract the time-window duration in minutes from an UpDown market question.
    "BTC Up or Down - 3:00AM-3:05AM ET"  → 5
    "BTC Up or Down - 3AM-4AM ET"         → 60
    "BTC 5 Minute Up or Down"             → 5   (new perpetual format)
    "BTC 15 Minute Up or Down"            → 15
    "BTC 1 Hour Up or Down"               → 60
    "BTC 4 Hour Up or Down"               → 240
    Returns None if the format isn't recognised.
    """
    import re as _re2
    q = question.lower()
    # New perpetual format: "N Minute" or "N Hour"
    m = _re2.search(r'(\d+)\s*(minute|min)\b', q)
    if m:
        return int(m.group(1))
    m = _re2.search(r'(\d+)\s*(hour|hr)\b', q)
    if m:
        return int(m.group(1)) * 60
    # Old per-slot format: "H:MMam-H:MMam"
    m = _re2.search(r'(\d{1,2}):(\d{2})\s*[ap]m\s*[-–]\s*(\d{1,2}):(\d{2})\s*[ap]m', q)
    if m:
        h1, mn1, h2, mn2 = int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4))
        delta = (h2 * 60 + mn2) - (h1 * 60 + mn1)
        if delta <= 0:
            delta += 12 * 60  # AM/PM rollover
        return delta
    # Old hourly format: "HAM-H+1AM"
    m = _re2.search(r'(\d{1,2})\s*[ap]m\s*[-–]\s*(\d{1,2})\s*[ap]m', q)
    if m:
        h1, h2 = int(m.group(1)), int(m.group(2))
        delta = (h2 - h1) * 60
        if delta <= 0:
            delta += 12 * 60
        return delta
    return None


class UpDownMomentumStrategy:
    """
    Trades Polymarket "XRP Up or Down - HH:MM-HH:MM" style markets.

    Logic:
      1. Detect the asset from the question.
      2. Measure the 60-second live price momentum from Binance.
      3. If momentum is strongly directional AND the market price for that
         direction is below our fair-value estimate, enter.

    Fair value model:
      - A market priced at 50¢ implies a coin flip.
      - If the asset is up +0.2% in the last 60s, we estimate the chance
        of it being "Up" at resolution is ~65%+ (momentum tends to persist
        over 5-min windows in liquid crypto markets).
      - We enter if market_price < fair_value - MIN_EDGE.
    """

    def __init__(self, min_momentum_pct: float = _MIN_MOMENTUM_PCT) -> None:
        self.min_momentum_pct = min_momentum_pct

    def analyse(self, market: Market, order_book: OrderBook | None) -> TradeSignal | None:
        symbol = _detect_updown_market(market.question)
        if symbol is None:
            return None

        # Warm up the price history on every call (lightweight, cached)
        live_price = _fetch_price(symbol)
        if live_price is None:
            return None

        # Multi-timeframe consensus: combines 30s + 60s + 5m + exchange pressure
        consensus, conf_label = _multitf_consensus(symbol)

        # Require at least MEDIUM confidence — LOW means only marginal cross-TF agreement
        # and fires too easily when price history is sparse.
        if conf_label in ("NONE", "LOW") or abs(consensus) < self.min_momentum_pct:
            m30 = _price_momentum_30s(symbol)
            m60 = _price_momentum_60s(symbol)
            hist_len = len(_PRICE_HISTORY.get(symbol.upper(), []))
            reason = (
                f"warming up — only {hist_len} price ticks so far (need ≥5 over ≥90s)"
                if hist_len < 5
                else f"momentum below threshold (conf={conf_label} consensus={consensus:+.4%})"
            )
            logger.debug(f"[UPDOWN SKIP] {symbol} \"{market.question[:50]}\" — {reason}")
            return None   # insufficient data or too weak

        # Map consensus strength → fair probability
        # Stronger multi-TF agreement → higher fair_prob → larger edge
        raw_confidence = 0.50 + min(abs(consensus) / 0.008, 1.0) * 0.44
        fair_prob = float(np.clip(raw_confidence, 0.52, 0.94))

        # Determine direction from consensus
        if consensus > 0:
            side = "YES"
            token = market.yes_token
            mkt_price = order_book.mid if order_book else market.yes_price
            fair_value = fair_prob
        else:
            side = "NO"
            token = market.no_token
            mkt_price = (1.0 - order_book.mid) if order_book else market.no_price
            fair_value = fair_prob

        fair_value = float(np.clip(fair_value, 0.01, 0.99))
        edge = fair_value - mkt_price

        if edge < config.MIN_EDGE:
            logger.debug(
                f"[UPDOWN SKIP] {symbol} edge={edge:+.3f} < min_edge={config.MIN_EDGE:.3f}  "
                f"fair={fair_value:.3f}  mkt={mkt_price:.3f}  conf={conf_label}"
            )
            return None

        confidence = conf_label  # already set by _multitf_consensus

        direction = "UP" if consensus > 0 else "DOWN"
        m30 = _price_momentum_30s(symbol) or 0.0
        m60 = _price_momentum_60s(symbol) or 0.0
        m5m = _price_momentum_5m(symbol) or 0.0
        pressure = _exchange_pressure(symbol)
        logger.info(
            f"[UPDOWN] {symbol} {direction}  "
            f"30s={m30:+.3%} 60s={m60:+.3%} 5m={m5m:+.3%} press={pressure:+.2f}  "
            f"fair={fair_value:.3f}  mkt={mkt_price:.3f}  edge={edge:+.3f}  "
            f"→ {side} [{confidence}]  \"{market.question[:45]}\""
        )

        # Pass both signals to the learner so it can attribute wins correctly:
        # momentum_signal = multi-TF consensus (price history driven)
        # imbalance_signal = Binance exchange pressure (order book driven)
        return TradeSignal(
            market_id=market.id,
            question=market.question,
            side=side,
            token_id=token.token_id,
            market_price=mkt_price,
            fair_value=fair_value,
            edge=edge,
            signal=float(np.clip(abs(consensus) * 200, 0.0, 1.0)),
            confidence=confidence,
            momentum_signal=float(consensus),
            imbalance_signal=float(pressure),
            is_latency_arb=False,
        )


# ═══════════════════════════════════════════════════════════════════════════
# Strategy 4: BTC Price Level Markets (daily above/below + monthly reach/dip)
# ═══════════════════════════════════════════════════════════════════════════
#
# Modelled on Attentive-Silica ($723K PNL in 1 month, 67% win rate):
#
#  Pattern A — Daily "above $X" safe yield
#    BTC safely above threshold → buy YES at 90-97¢, collect 3-7% edge.
#
#  Pattern B — Monthly/weekly "reach $X" cheap options
#    Buy YES at 0.4-2¢ when true touch probability is 5-30%.
#    Market massively underprices BTC volatility on far-out levels.
#    This is how the +$195K trade (+7,360%) happened.
#
# ═══════════════════════════════════════════════════════════════════════════

import math as _math


def _norm_cdf(z: float) -> float:
    """Fast normal CDF (Abramowitz & Stegun)."""
    if z >= 8.0:  return 1.0
    if z <= -8.0: return 0.0
    t = 1.0 / (1.0 + 0.2316419 * abs(z))
    d = 0.3989423 * _math.exp(-z * z / 2.0)
    p = d * t * (0.3193815 + t * (-0.3565638 + t * (1.7814779 + t * (-1.8212560 + t * 1.3302744))))
    return (1.0 - p) if z >= 0 else p


def _prob_above(current: float, threshold: float, days: float, daily_vol: float = 0.04) -> float:
    """P(log-normal price ends above threshold after `days` days)."""
    if days <= 0:
        return 1.0 if current >= threshold else 0.0
    vol = daily_vol * _math.sqrt(days)
    z   = _math.log(current / threshold) / vol
    return _norm_cdf(z)


def _prob_touch(current: float, target: float, days: float, daily_vol: float = 0.04) -> float:
    """
    P(price touches `target` at any point over `days` days).
    Reflection principle: P(touch) = 2 * N(-|log(current/target)| / vol).
    """
    if days <= 0:
        return 0.0
    vol      = daily_vol * _math.sqrt(days)
    log_dist = abs(_math.log(current / target))
    return min(2.0 * _norm_cdf(-log_dist / vol), 0.999)


def _parse_btc_level(question: str):
    """
    Parse a BTC price-level question.
    Returns (mtype, p1, p2) or None.
    mtype: 'above' | 'below' | 'between' | 'reach' | 'dip'
    """
    q = question.lower()
    if "bitcoin" not in q and "btc" not in q:
        return None

    def _px(s: str) -> float | None:
        s = s.replace(",", "").strip()
        m = _re.match(r"(\d+(?:\.\d+)?)([kmb]?)", s)
        if not m:
            return None
        v   = float(m.group(1))
        mul = {"k": 1_000, "m": 1_000_000, "b": 1_000_000_000}.get(m.group(2), 1)
        return v * mul

    for pat, mtype in (
        (r"(?:be\s+)?(?:above|greater\s+than)\s+\$?([\d,]+(?:\.\d+)?)", "above"),
        (r"(?:be\s+)?(?:less\s+than|below)\s+\$?([\d,]+(?:\.\d+)?)",    "below"),
        (r"reach\s+\$?([\d,]+(?:\.\d+)?)",                               "reach"),
        (r"dip\s+to\s+\$?([\d,]+(?:\.\d+)?)",                            "dip"),
    ):
        m = _re.search(pat, q)
        if m:
            p = _px(m.group(1))
            return (mtype, p, None) if p else None

    m = _re.search(r"between\s+\$?([\d,]+)\s+and\s+\$?([\d,]+)", q)
    if m:
        p1, p2 = _px(m.group(1)), _px(m.group(2))
        return ("between", p1, p2) if p1 and p2 else None

    return None


class BTCLevelStrategy:
    """
    Trades BTC daily/weekly/monthly price level markets.

    Four sub-patterns run simultaneously:

    A) Daily above/below  — safe yield when BTC is far from threshold.
    B) Weekly above/below — moderate certainty, multi-day window.
    C) Reach/dip cheap options — buy YES at <5¢ when fair prob is 3×+
       the market price. The +$195K trade was this pattern.
    D) Range (between) — buy NO when BTC is far outside the range.
    """

    _DAILY_VOL             = 0.04   # 4% daily BTC vol (conservative)
    _MIN_CHEAP_RATIO       = 3.0    # fair / market must be >= 3× for cheap options
    _CHEAP_OPTION_MAX_PRICE = 0.05  # only pattern C when market price <= 5¢

    def analyse(self, market: Market, order_book: OrderBook | None) -> TradeSignal | None:
        parsed = _parse_btc_level(market.question)
        if parsed is None:
            return None

        mtype, p1, p2 = parsed
        current_btc = _fetch_price("BTC")
        if not current_btc or not p1:
            return None

        # Days to resolution
        days = 1.0
        if market.end_date:
            try:
                from datetime import datetime, timezone as _tz
                end  = datetime.fromisoformat(market.end_date.replace("Z", "+00:00"))
                days = max(0.05, (end - datetime.now(_tz.utc)).total_seconds() / 86400)
            except Exception:
                pass

        mkt_yes = order_book.mid if order_book else market.yes_price
        mkt_no  = 1.0 - mkt_yes

        # ── Fair probabilities ────────────────────────────────────────────
        if mtype == "above":
            fair_yes = _prob_above(current_btc, p1, days, self._DAILY_VOL)
        elif mtype == "below":
            fair_yes = 1.0 - _prob_above(current_btc, p1, days, self._DAILY_VOL)
        elif mtype in ("reach", "dip"):
            fair_yes = _prob_touch(current_btc, p1, days, self._DAILY_VOL)
        elif mtype == "between":
            fair_yes = (_prob_above(current_btc, p1, days, self._DAILY_VOL)
                        - _prob_above(current_btc, p2, days, self._DAILY_VOL))
        else:
            return None

        fair_yes = float(np.clip(fair_yes, 0.001, 0.999))
        fair_no  = 1.0 - fair_yes
        edge_yes = fair_yes - mkt_yes
        edge_no  = fair_no  - mkt_no

        # ── Pattern C: cheap touch options ────────────────────────────────
        if mtype in ("reach", "dip") and mkt_yes <= self._CHEAP_OPTION_MAX_PRICE:
            ratio = fair_yes / max(mkt_yes, 0.001)
            if ratio >= self._MIN_CHEAP_RATIO:
                confidence = "HIGH" if ratio >= 8 else "MEDIUM" if ratio >= 5 else "LOW"
                logger.info(
                    f"[BTC-LEVEL CHEAP] {mtype.upper()} ${p1:,.0f}  BTC=${current_btc:,.0f}  "
                    f"fair={fair_yes:.3f}  mkt={mkt_yes:.4f}  ratio={ratio:.1f}×  days={days:.0f}  "
                    f"→ YES [{confidence}]  \"{market.question[:50]}\""
                )
                return TradeSignal(
                    market_id=market.id,
                    question=market.question,
                    side="YES",
                    token_id=market.yes_token.token_id,
                    market_price=mkt_yes,
                    fair_value=fair_yes,
                    edge=fair_yes - mkt_yes,
                    signal=fair_yes - mkt_yes,
                    confidence=confidence,
                    is_latency_arb=False,
                )

        # ── Patterns A/B/D: standard edge threshold ───────────────────────
        if edge_yes >= edge_no and edge_yes > config.MIN_EDGE:
            side, token, mkt_p, fair_p, edge = "YES", market.yes_token, mkt_yes, fair_yes, edge_yes
        elif edge_no > config.MIN_EDGE:
            side, token, mkt_p, fair_p, edge = "NO",  market.no_token,  mkt_no,  fair_no,  edge_no
        else:
            return None

        confidence = "HIGH" if edge > 0.15 else "MEDIUM" if edge > 0.08 else "LOW"
        logger.info(
            f"[BTC-LEVEL] {mtype.upper()} ${p1:,.0f}  BTC=${current_btc:,.0f}  "
            f"fair={fair_p:.3f}  mkt={mkt_p:.3f}  edge={edge:+.3f}  days={days:.1f}  "
            f"→ {side} [{confidence}]  \"{market.question[:50]}\""
        )
        return TradeSignal(
            market_id=market.id,
            question=market.question,
            side=side,
            token_id=token.token_id,
            market_price=mkt_p,
            fair_value=fair_p,
            edge=edge,
            signal=edge,
            confidence=confidence,
            is_latency_arb=False,
        )


_PREV_PRICES: dict[str, float] = {}   # market_id → last YES price

# ═══════════════════════════════════════════════════════════════════════════
# Strategy 8: News Arbitrage  (headline sentiment vs market price)
# ═══════════════════════════════════════════════════════════════════════════
#
# When a relevant news headline breaks, Polymarket markets may not have
# repriced yet.  This strategy:
#   1. Looks up recent headlines (24h memory) relevant to the market question.
#   2. Computes aggregate sentiment from those headlines.
#   3. If sentiment strongly disagrees with the current market price, enters.
#
# Example: "Fed cuts rates unexpectedly" → sentiment +1 for BTC markets
#   BTC market still priced at 0.45 → big edge to buy YES.
#
# Uses the news_learner (separate AdaptiveLearner) so news trades don't
# pollute momentum/imbalance strategy statistics.
# ═══════════════════════════════════════════════════════════════════════════


def update_price_snapshot(market_id: str, yes_price: float) -> None:
    _PREV_PRICES[market_id] = yes_price


class NewsEventStrategy:
    """
    Momentum follow on sudden market price moves.

    If a market's YES price moved ≥ JUMP_THRESHOLD since last scan,
    follow the direction — the move likely reflects breaking news that
    hasn't fully propagated through the market yet.

    This is the "Trump tariff announcement" pattern: market goes from
    40¢ to 75¢ in one loop. We catch the remaining 25¢ move.
    """

    JUMP_THRESHOLD = 0.12   # 12% sudden move triggers the signal
    MIN_EDGE       = 0.08   # minimum remaining edge after the jump

    def analyse(self, market: Market, order_book: OrderBook | None) -> TradeSignal | None:
        prev = _PREV_PRICES.get(market.id)
        current = order_book.mid if order_book else market.yes_price
        update_price_snapshot(market.id, current)

        if prev is None:
            return None   # first time seeing this market

        move = current - prev
        if abs(move) < self.JUMP_THRESHOLD:
            return None

        # Follow the move direction
        if move > 0:
            # YES jumped — buy YES (momentum continuation)
            fair_yes = min(current + move * 0.5, 0.97)   # extrapolate 50% more
            edge = fair_yes - current
            if edge < self.MIN_EDGE:
                return None
            side, token, mkt_p, fair_p = "YES", market.yes_token, current, fair_yes
        else:
            # YES dumped — buy NO
            fair_no  = min((1 - current) + abs(move) * 0.5, 0.97)
            mkt_no   = 1.0 - current
            edge     = fair_no - mkt_no
            if edge < self.MIN_EDGE:
                return None
            side, token, mkt_p, fair_p = "NO", market.no_token, mkt_no, fair_no

        confidence = "HIGH" if abs(move) > 0.25 else "MEDIUM"
        logger.info(
            f"[NEWS-EVENT] {market.question[:55]}  "
            f"prev={prev:.3f}  now={current:.3f}  move={move:+.3f}  "
            f"→ {side} [{confidence}]"
        )
        return TradeSignal(
            market_id=market.id,
            question=market.question,
            side=side,
            token_id=token.token_id,
            market_price=mkt_p,
            fair_value=fair_p,
            edge=edge,
            signal=move,
            confidence=confidence,
            is_latency_arb=False,  # use Kelly sizing
        )


class NewsArbitrageStrategy:
    """
    Trades markets where recent news headlines strongly disagree with the
    current market price.

    Algorithm:
      1. Fetch up to MAX_HEADLINES recent headlines relevant to this market
         from the NewsFeed 24h memory.
      2. Average their sentiment scores (−1 = bearish, +1 = bullish).
      3. Compute an implied "should-be" probability from sentiment:
           avg_sentiment ≥ +MIN_SENTIMENT → fair_yes ≈ 0.65–0.85
           avg_sentiment ≤ −MIN_SENTIMENT → fair_no ≈ 0.65–0.85
      4. Enter when edge > MIN_EDGE.

    Trades are tagged is_news_arb=True so they go through the separate
    news AdaptiveLearner and count against the daily news trade cap.
    """

    MIN_SENTIMENT  = 0.50   # minimum absolute avg sentiment to act (raised from 0.20)
    MIN_EDGE       = 0.08   # minimum edge after fair-value estimate
    MIN_RELEVANCE  = 0.20   # minimum news score against market question
    MAX_HEADLINES  = 5      # use top-5 most relevant headlines
    MIN_HEADLINES  = 2      # require at least 2 matching headlines

    def __init__(self, news_feed) -> None:
        """news_feed: a NewsFeed instance (imported lazily to avoid circular dep)."""
        self._feed = news_feed

    def analyse(self, market: Market, order_book: OrderBook | None) -> TradeSignal | None:
        try:
            # News sentiment cannot predict 5-minute price windows — skip UpDown markets
            if _detect_updown_market(market.question) is not None:
                return None

            headlines = self._feed.recent_for_market(
                market.question,
                max_results=self.MAX_HEADLINES,
                min_score=self.MIN_RELEVANCE,
            )
            if not headlines or len(headlines) < self.MIN_HEADLINES:
                return None

            sentiments = [h.sentiment for h in headlines]
            avg_sent   = sum(sentiments) / len(sentiments)

            if abs(avg_sent) < self.MIN_SENTIMENT:
                return None   # too weak or mixed

            mkt_yes = order_book.mid if order_book else market.yes_price
            mkt_no  = 1.0 - mkt_yes

            # Map sentiment magnitude to fair probability (0.65 at MIN, 0.85 at ±1.0)
            strength  = min(abs(avg_sent), 1.0)
            fair_prob = 0.50 + strength * 0.35   # 0.50 → 0.85

            if avg_sent > 0:
                # Bullish headlines → favour YES
                fair_yes  = float(np.clip(fair_prob, 0.01, 0.99))
                fair_no   = 1.0 - fair_yes
                edge_yes  = fair_yes - mkt_yes
                edge_no   = fair_no  - mkt_no
                if edge_yes >= edge_no and edge_yes >= self.MIN_EDGE:
                    side, token, mkt_p, fair_p, edge = "YES", market.yes_token, mkt_yes, fair_yes, edge_yes
                elif edge_no >= self.MIN_EDGE:
                    side, token, mkt_p, fair_p, edge = "NO",  market.no_token,  mkt_no,  fair_no,  edge_no
                else:
                    return None
            else:
                # Bearish headlines → favour NO
                fair_no   = float(np.clip(fair_prob, 0.01, 0.99))
                fair_yes  = 1.0 - fair_no
                edge_yes  = fair_yes - mkt_yes
                edge_no   = fair_no  - mkt_no
                if edge_no >= edge_yes and edge_no >= self.MIN_EDGE:
                    side, token, mkt_p, fair_p, edge = "NO",  market.no_token,  mkt_no,  fair_no,  edge_no
                elif edge_yes >= self.MIN_EDGE:
                    side, token, mkt_p, fair_p, edge = "YES", market.yes_token, mkt_yes, fair_yes, edge_yes
                else:
                    return None

            confidence = "HIGH" if abs(avg_sent) > 0.6 else "MEDIUM" if abs(avg_sent) > 0.35 else "LOW"

            top = headlines[0].title[:50]
            logger.info(
                f"[NEWS-ARB] \"{market.question[:55]}\"  "
                f"headlines={len(headlines)}  avg_sent={avg_sent:+.2f}  "
                f"fair={fair_p:.3f}  mkt={mkt_p:.3f}  edge={edge:+.3f}  "
                f"→ {side} [{confidence}]  top: \"{top}\""
            )

            return TradeSignal(
                market_id=market.id,
                question=market.question,
                side=side,
                token_id=token.token_id,
                market_price=mkt_p,
                fair_value=fair_p,
                edge=edge,
                signal=avg_sent,
                confidence=confidence,
                momentum_signal=0.0,
                imbalance_signal=avg_sent,
                is_latency_arb=False,
                is_news_arb=True,
            )

        except Exception as exc:
            logger.warning(f"[NEWS-ARB] Error on {market.id}: {exc}")
            return None
