"""
Trading strategies for Polymarket.

Strategy 1 — Momentum + Order-Book Imbalance
─────────────────────────────────────────────
Combines 24-h price momentum with order-book bid/ask imbalance.
Signal weights, thresholds, and adjustments are all dynamic — the
AdaptiveLearner can tune them online based on trade outcomes.

Strategy 2 — Latency Arbitrage (BTC / crypto contracts)
───────────────────────────────────────────────────────
Polymarket updates crypto-outcome contract prices slower than real-time
exchange feeds.  This strategy:
  1. Pulls the live BTC (or other asset) price from external feeds.
  2. Compares it to the implied price in the Polymarket contract.
  3. When the lag exceeds a configurable threshold it places a rapid
     limit order to capture the mispricing before the market catches up.
"""
from __future__ import annotations

import time
from dataclasses import dataclass
from typing import TYPE_CHECKING

import numpy as np
import requests
from loguru import logger

from src.client import Market, OrderBook, PricePoint
import config

if TYPE_CHECKING:
    from src.learner import StrategyParams

# ---------------------------------------------------------------------------
# Defaults (used when no adaptive params are provided)
# ---------------------------------------------------------------------------

DEFAULT_SIGNAL_THRESHOLD = 0.15
DEFAULT_MAX_SIGNAL_ADJUST = 0.07
DEFAULT_MOMENTUM_WEIGHT = 0.50
DEFAULT_IMBALANCE_WEIGHT = 0.50
OB_LEVELS = 10
MOMENTUM_NORMALISER = 0.20


# ---------------------------------------------------------------------------
# Output dataclass
# ---------------------------------------------------------------------------

@dataclass
class TradeSignal:
    market_id: str
    question: str
    side: str            # "YES" | "NO"
    token_id: str
    market_price: float  # current market mid price for the chosen token
    fair_value: float    # our estimated fair price
    edge: float          # fair_value - market_price (positive = we have edge)
    signal: float        # composite signal [-1, 1]
    confidence: str      # "LOW" | "MEDIUM" | "HIGH"
    # Sub-signals (used by learner to attribute wins/losses)
    momentum_signal: float  = 0.0
    imbalance_signal: float = 0.0
    # Latency arb fields
    is_latency_arb: bool = False
    lag_pct: float = 0.0
    # Time urgency (hours until market closes; None = unknown)
    hours_to_close: float | None = None
    # Best ask at signal time — used for aggressive fills on ultra-short markets
    best_ask: float | None = None
    # Set True for trades generated by NewsArbitrageStrategy — routed to news learner
    is_news_arb: bool = False

    def __str__(self) -> str:
        tag = "[LATENCY-ARB] " if self.is_latency_arb else ""
        return (
            f"{tag}[{self.confidence}] {self.side} {self.question[:60]} | "
            f"mkt={self.market_price:.3f}  fv={self.fair_value:.3f}  "
            f"edge={self.edge:+.3f}  sig={self.signal:+.3f}"
        )


# ═══════════════════════════════════════════════════════════════════════════
# Strategy 1: Momentum + Imbalance
# ═══════════════════════════════════════════════════════════════════════════

class MomentumImbalanceStrategy:
    """
    Scans a single market and returns a TradeSignal if an opportunity is
    found.  All tuneable constants come from `params` (set by the learner).
    """

    def __init__(self, params: StrategyParams | None = None) -> None:
        self._params = params

    # -- properties for current param values (fallback to defaults) --------

    @property
    def _momentum_weight(self) -> float:
        return self._params.momentum_weight if self._params else DEFAULT_MOMENTUM_WEIGHT

    @property
    def _imbalance_weight(self) -> float:
        return self._params.imbalance_weight if self._params else DEFAULT_IMBALANCE_WEIGHT

    @property
    def _signal_threshold(self) -> float:
        return self._params.signal_threshold if self._params else DEFAULT_SIGNAL_THRESHOLD

    @property
    def _max_signal_adjust(self) -> float:
        return self._params.max_signal_adjust if self._params else DEFAULT_MAX_SIGNAL_ADJUST

    # -- analysis ----------------------------------------------------------

    def analyse(
        self,
        market: Market,
        order_book: OrderBook | None,
        price_history: list[PricePoint],
    ) -> TradeSignal | None:
        try:
            mom_sig = self._momentum_signal(market, price_history)
            imb_sig = self._imbalance_signal(order_book)

            composite = (
                self._momentum_weight * mom_sig
                + self._imbalance_weight * imb_sig
            )

            logger.debug(
                f"{market.question[:50]} | mom={mom_sig:+.3f}  "
                f"imb={imb_sig:+.3f}  comp={composite:+.3f}"
            )

            if abs(composite) < self._signal_threshold:
                return None

            # Choose direction
            if composite > 0:
                side = "YES"
                token = market.yes_token
                mid = order_book.mid if order_book else market.yes_price
            else:
                side = "NO"
                token = market.no_token
                mid = (1.0 - order_book.mid) if order_book else market.no_price
                composite = -composite  # flip for edge calc

            fair_value = mid * (1.0 + composite * self._max_signal_adjust)
            fair_value = float(np.clip(fair_value, 0.01, 0.99))
            edge = fair_value - mid

            if edge < config.MIN_EDGE:
                return None

            confidence = (
                "HIGH"   if composite > 0.5 else
                "MEDIUM" if composite > 0.3 else
                "LOW"
            )

            return TradeSignal(
                market_id=market.id,
                question=market.question,
                side=side,
                token_id=token.token_id,
                market_price=mid,
                fair_value=fair_value,
                edge=edge,
                signal=composite,
                confidence=confidence,
                momentum_signal=mom_sig,
                imbalance_signal=imb_sig,
            )

        except Exception as exc:
            logger.warning(f"Strategy error on market {market.id}: {exc}")
            return None

    # -- sub-signals -------------------------------------------------------

    def _momentum_signal(
        self, market: Market, price_history: list[PricePoint]
    ) -> float:
        if len(price_history) < 2:
            return 0.0
        recent = price_history[-1].price
        lookback = min(24, len(price_history) - 1)
        past = price_history[-1 - lookback].price
        if past <= 0:
            return 0.0
        change = (recent - past) / past
        return float(np.clip(change / MOMENTUM_NORMALISER, -1.0, 1.0))

    def _imbalance_signal(self, ob: OrderBook | None) -> float:
        if ob is None:
            return 0.0
        bid_qty = sum(float(b.get("size", 0)) for b in ob.bids[:OB_LEVELS])
        ask_qty = sum(float(a.get("size", 0)) for a in ob.asks[:OB_LEVELS])
        total = bid_qty + ask_qty
        if total == 0:
            return 0.0
        return float((bid_qty - ask_qty) / total)


# ═══════════════════════════════════════════════════════════════════════════
# Strategy 2: Latency Arbitrage
# ═══════════════════════════════════════════════════════════════════════════

# ── Price feeds ──────────────────────────────────────────────────────────────
# Binance is the fastest public feed; CoinGecko is fallback (rate-limited)
_BINANCE_FEEDS: dict[str, str] = {
    "BTC":  "https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT",
    "ETH":  "https://api.binance.com/api/v3/ticker/price?symbol=ETHUSDT",
    "XRP":  "https://api.binance.com/api/v3/ticker/price?symbol=XRPUSDT",
    "SOL":  "https://api.binance.com/api/v3/ticker/price?symbol=SOLUSDT",
    "DOGE": "https://api.binance.com/api/v3/ticker/price?symbol=DOGEUSDT",
}
_COINGECKO_IDS: dict[str, str] = {
    "BTC":  "bitcoin",
    "ETH":  "ethereum",
    "XRP":  "ripple",
    "SOL":  "solana",
    "DOGE": "dogecoin",
}

_PRICE_CACHE: dict[str, tuple[float, float]] = {}     # symbol → (price, timestamp)
_EXCHANGE_PRESSURE: dict[str, float] = {}            # symbol → bid/ask imbalance (-1..+1)
_CACHE_TTL = 2.0   # seconds

# Rolling 60-second price history for momentum: symbol → [(price, ts), ...]
_PRICE_HISTORY: dict[str, list[tuple[float, float]]] = {}
_HISTORY_WINDOW = 600  # keep 10 minutes of ticks for multi-timeframe analysis


def _fetch_price(symbol: str) -> float | None:
    """Fetch live price for any supported symbol (cached 2 s)."""
    sym = symbol.upper()
    cached = _PRICE_CACHE.get(sym)
    if cached and (time.time() - cached[1]) < _CACHE_TTL:
        return cached[0]

    price: float | None = None

    # Try Binance first (fastest, no rate limit for single ticker)
    if sym in _BINANCE_FEEDS:
        try:
            r = requests.get(_BINANCE_FEEDS[sym], timeout=3)
            r.raise_for_status()
            price = float(r.json()["price"])
        except Exception:
            pass

    # Fall back to CoinGecko
    if price is None and sym in _COINGECKO_IDS:
        try:
            cg_id = _COINGECKO_IDS[sym]
            r = requests.get(
                f"https://api.coingecko.com/api/v3/simple/price?ids={cg_id}&vs_currencies=usd",
                timeout=4,
            )
            r.raise_for_status()
            price = float(r.json()[cg_id]["usd"])
        except Exception:
            pass

    if price is not None:
        _PRICE_CACHE[sym] = (price, time.time())
        # Record in rolling history
        hist = _PRICE_HISTORY.setdefault(sym, [])
        now = time.time()
        hist.append((price, now))
        # Trim to window
        cutoff = now - _HISTORY_WINDOW
        _PRICE_HISTORY[sym] = [(p, t) for p, t in hist if t >= cutoff]

    return price


def _fetch_btc_price() -> float | None:
    """Backward-compatible wrapper."""
    return _fetch_price("BTC")


def _price_momentum(symbol: str, window_secs: int) -> float | None:
    """
    Returns the % price change over the last `window_secs` seconds.
    Positive = rising, negative = falling. None if insufficient history.
    """
    hist = _PRICE_HISTORY.get(symbol.upper(), [])
    now = time.time()
    window = [(p, t) for p, t in hist if now - t <= window_secs * 1.25]
    if len(window) < 2:
        return None
    oldest_price = window[0][0]
    newest_price = window[-1][0]
    if oldest_price <= 0:
        return None
    return (newest_price - oldest_price) / oldest_price


def _price_momentum_60s(symbol: str) -> float | None:
    return _price_momentum(symbol, 60)


def _price_momentum_30s(symbol: str) -> float | None:
    return _price_momentum(symbol, 30)


def _price_momentum_5m(symbol: str) -> float | None:
    return _price_momentum(symbol, 300)


def _price_acceleration(symbol: str) -> float | None:
    """
    Returns how much momentum is changing (2nd derivative of price).
    Positive = trend is speeding up, negative = trend is slowing/reversing.
    Computed as: mom_30s - mom_60s (scaled to same units).
    Returns None if insufficient data.
    """
    m30 = _price_momentum_30s(symbol)
    m60 = _price_momentum_60s(symbol)
    if m30 is None or m60 is None:
        return None
    # Annualise to same time scale: m30 is over 30s, m60 over 60s
    # Acceleration = recent 30s rate vs older 60s rate
    m30_scaled = m30 * 2.0   # scale 30s → 60s equivalent
    return m30_scaled - m60


def _exchange_pressure(symbol: str) -> float:
    """
    Returns Binance bid/ask size imbalance for `symbol`.
    Range: -1 (heavy ask pressure, likely falling) to +1 (heavy bid pressure, likely rising).
    0.0 if no data available.
    """
    return _EXCHANGE_PRESSURE.get(symbol.upper(), 0.0)


def _multitf_consensus(symbol: str) -> tuple[float, str]:
    """
    Combines 30s, 60s, 5m momentum + exchange pressure into a single
    directional score and confidence.

    Returns: (direction_score, confidence)
      direction_score: positive = UP, negative = DOWN, magnitude = strength
      confidence: "HIGH" | "MEDIUM" | "LOW" | "NONE" (insufficient data)
    """
    sym = symbol.upper()
    hist = _PRICE_HISTORY.get(sym, [])

    # Require at least 5 distinct ticks AND 90 seconds of real price history.
    # With fewer ticks, all three timeframes return the same value (same 1-2 points
    # fall in every window) — this looks like strong agreement but is just noise.
    if len(hist) < 5:
        return 0.0, "NONE"
    time_span = hist[-1][1] - hist[0][1]
    if time_span < 90:
        return 0.0, "NONE"

    m30 = _price_momentum_30s(sym)
    m60 = _price_momentum_60s(sym)
    m5m = _price_momentum_5m(sym)
    pressure = _exchange_pressure(sym)
    accel = _price_acceleration(sym)

    available = sum(x is not None for x in [m30, m60, m5m])
    if available < 2:
        return 0.0, "NONE"

    # Reject signals where all available timeframes are identical — that means
    # only one distinct price exists in the history window (still warming up).
    vals = [x for x in [m30, m60, m5m] if x is not None]
    if len(vals) >= 2 and len(set(round(v, 8) for v in vals)) == 1:
        return 0.0, "NONE"

    signals = []
    if m30 is not None:
        signals.append(m30 * 2.0)     # 30s scaled to 60s units, weight 1.0×
    if m60 is not None:
        signals.append(m60 * 1.0)     # 60s baseline, weight 1.0×
    if m5m is not None:
        signals.append(m5m * 0.2)     # 5m smoothed, weight 0.2× (directional only)
    if pressure != 0.0:
        signals.append(pressure * 0.003)  # convert to % units

    consensus = sum(signals) / len(signals)

    # Check cross-timeframe agreement — all pointing same direction = higher confidence
    directions = []
    if m30 is not None:
        directions.append(1 if m30 > 0 else -1)
    if m60 is not None:
        directions.append(1 if m60 > 0 else -1)
    if m5m is not None:
        directions.append(1 if m5m > 0 else -1)
    if pressure != 0.0:
        directions.append(1 if pressure > 0.1 else (-1 if pressure < -0.1 else 0))

    n_agree = sum(d == (1 if consensus > 0 else -1) for d in directions if d != 0)
    n_total = sum(d != 0 for d in directions)
    agreement_ratio = n_agree / n_total if n_total > 0 else 0.5

    # Acceleration bonus: trend speeding up = more conviction
    accel_bonus = 0.0
    if accel is not None and (accel > 0) == (consensus > 0):
        accel_bonus = min(abs(accel) * 0.3, 0.002)

    strength = abs(consensus) + accel_bonus

    if agreement_ratio >= 0.75 and strength >= 0.004:
        conf = "HIGH"
    elif agreement_ratio >= 0.60 and strength >= 0.003:
        conf = "MEDIUM"
    elif agreement_ratio >= 0.50 and strength >= 0.002:
        conf = "LOW"
    else:
        conf = "NONE"

    return consensus, conf


# Keyword patterns that indicate BTC price-level contracts
_BTC_KEYWORDS = [
    "bitcoin", "btc", "btc/usd", "bitcoin price",
]


def _extract_btc_target(question: str) -> float | None:
    """
    Try to extract the dollar target from a market question like:
      "Will Bitcoin be above $70,000 on June 30?"
      "Will Bitcoin hit $100k by year end?"
      "Will Bitcoin reach $1m before GTA VI?"
    Returns the dollar figure or None.
    """
    q = question.lower()
    if not any(kw in q for kw in _BTC_KEYWORDS):
        return None

    import re
    # Match $70,000 / $70k / $1m / $1.5b with optional suffix k/m/b
    m = re.search(r"\$\s*([\d,]+(?:\.\d+)?)\s*([kmb])(?:\b|$)", q)
    if m:
        try:
            val = float(m.group(1).replace(",", ""))
            suffix = m.group(2)
            if suffix == "k":
                val *= 1_000
            elif suffix == "m":
                val *= 1_000_000
            elif suffix == "b":
                val *= 1_000_000_000
            return val
        except ValueError:
            pass

    # Fall back: plain number like $70,000 or $70000
    m = re.search(r"\$([\d,]+(?:\.\d+)?)", q)
    if not m:
        return None
    try:
        val = float(m.group(1).replace(",", ""))
        # Numbers under 500 are probably written as "70" meaning 70k
        if val < 500:
            val *= 1000
        return val
    except ValueError:
        return None


class LatencyArbStrategy:
    """
    Detects when Polymarket crypto contracts lag behind real-time price feeds
    and generates a signal to exploit the mispricing.

    Parameters:
        min_lag_pct – minimum % divergence to act on (default 0.3 %)
    """

    def __init__(self, min_lag_pct: float = 0.003) -> None:
        self.min_lag_pct = min_lag_pct

    def analyse(self, market: Market, order_book: OrderBook | None) -> TradeSignal | None:
        target = _extract_btc_target(market.question)
        if target is None:
            return None  # not a BTC price market

        live_price = _fetch_btc_price()
        if live_price is None:
            return None

        # Safety: skip markets where the live price is more than 30% away from
        # the target — those are long-dated prediction markets (e.g. "Will BTC
        # hit $1M?"), not genuine latency-arb opportunities.
        distance_pct = abs(live_price - target) / target
        if distance_pct > 0.30:
            logger.debug(
                f"[LATENCY-ARB] Skipping {market.question[:50]} — "
                f"BTC ${live_price:,.0f} is {distance_pct:.0%} away from "
                f"target ${target:,.0f} (threshold 30%)"
            )
            return None

        # Implied probability: how likely is BTC to be above $target?
        # Simple model: if live BTC is far above target → probability ≈ 1,
        # if far below → ≈ 0, linear in the band ±10 % around target.
        band = target * 0.10
        implied_prob = float(np.clip((live_price - target + band) / (2 * band), 0.01, 0.99))

        # Market probability
        mkt_yes = order_book.mid if order_book else market.yes_price

        lag = implied_prob - mkt_yes          # positive → market is too low → buy YES
        lag_pct = abs(lag)

        if lag_pct < self.min_lag_pct:
            return None

        if lag > 0:
            side = "YES"
            token = market.yes_token
            mkt_price = mkt_yes
        else:
            side = "NO"
            token = market.no_token
            mkt_price = 1.0 - mkt_yes

        fair_value = float(np.clip(implied_prob if side == "YES" else 1.0 - implied_prob, 0.01, 0.99))
        edge = fair_value - mkt_price

        if edge < config.MIN_EDGE:
            return None

        confidence = (
            "HIGH"   if lag_pct > 0.01 else
            "MEDIUM" if lag_pct > 0.005 else
            "LOW"
        )

        logger.info(
            f"[LATENCY-ARB] BTC live=${live_price:,.0f}  target=${target:,.0f}  "
            f"implied={implied_prob:.3f}  mkt={mkt_yes:.3f}  lag={lag:+.4f} "
            f"→ {side}"
        )

        return TradeSignal(
            market_id=market.id,
            question=market.question,
            side=side,
            token_id=token.token_id,
            market_price=mkt_price,
            fair_value=fair_value,
            edge=edge,
            signal=lag_pct,
            confidence=confidence,
            momentum_signal=0.0,
            imbalance_signal=0.0,
            is_latency_arb=True,
            lag_pct=lag_pct,
        )


# ═══════════════════════════════════════════════════════════════════════════
# Strategy 3: Up/Down 5-Minute Momentum
# ═══════════════════════════════════════════════════════════════════════════

import re as _re

# Maps keywords in the market question to the Binance symbol to fetch
_UPDOWN_ASSETS = {
    "xrp":      "XRP",
    "ripple":   "XRP",
    "btc":      "BTC",
    "bitcoin":  "BTC",
    "eth":      "ETH",
    "ethereum": "ETH",
    "sol":      "SOL",
    "solana":   "SOL",
    "doge":     "DOGE",
    "dogecoin": "DOGE",
    "bnb":      "BNB",
    "hype":     "HYPE",
}

# Minimum absolute 60s momentum to act on (0.05% move in 60s)
_MIN_MOMENTUM_PCT = 0.0005


def _detect_updown_market(question: str) -> str | None:
    """
    Returns the asset symbol if the question is an Up/Down short-interval
    crypto market.  Handles all Polymarket question phrasings:
      • "XRP Up or Down - March 3, 12:00PM-12:05PM ET"
      • "Will BTC be higher or lower in 15 minutes?"
      • "Bitcoin higher or lower in the next 5 min?"
      • "BTC up/down 15m"
    Returns None otherwise.
    """
    q = question.lower()
    # Must contain a directional phrase
    direction_phrases = (
        "up or down", "up/down", "higher or lower",
        "higher in", "lower in", "go up", "go down",
        "be up", "be down",
    )
    # Must also reference a short time interval to avoid false positives
    # on long-term questions like "Will BTC be higher by end of year?"
    time_phrases = (
        "5 min", "5min", "15 min", "15min", "5-min", "15-min",
        "5 minute", "15 minute", "next 5", "next 15",
        "in 5", "in 15", ":00pm", ":05pm", ":10pm", ":15pm",
        ":20pm", ":25pm", ":30pm", ":35pm", ":40pm", ":45pm",
        ":50pm", ":55pm", ":00am", ":05am", ":10am", ":15am",
    )
    has_direction = any(p in q for p in direction_phrases)
    has_time      = any(p in q for p in time_phrases)
    # "up or down" alone is strong enough (e.g. "XRP Up or Down - 12:00PM-12:05PM")
    if not has_direction:
        return None
    # For "higher or lower" we require a time phrase to avoid false positives
    if "higher or lower" in q and not has_time:
        return None
    for kw, sym in _UPDOWN_ASSETS.items():
        if kw in q:
            return sym
    return None


def _updown_window_mins(question: str) -> int | None:
    """
    Extract the time-window duration in minutes from an UpDown market question.
    "BTC Up or Down - 3:00AM-3:05AM ET"  → 5
    "BTC Up or Down - 3AM-4AM ET"         → 60
    "BTC 5 Minute Up or Down"             → 5   (new perpetual format)
    "BTC 15 Minute Up or Down"            → 15
    "BTC 1 Hour Up or Down"               → 60
    "BTC 4 Hour Up or Down"               → 240
    Returns None if the format isn't recognised.
    """
    import re as _re2
    q = question.lower()
    # New perpetual format: "N Minute" or "N Hour"
    m = _re2.search(r'(\d+)\s*(minute|min)\b', q)
    if m:
        return int(m.group(1))
    m = _re2.search(r'(\d+)\s*(hour|hr)\b', q)
    if m:
        return int(m.group(1)) * 60
    # Old per-slot format: "H:MMam-H:MMam"
    m = _re2.search(r'(\d{1,2}):(\d{2})\s*[ap]m\s*[-–]\s*(\d{1,2}):(\d{2})\s*[ap]m', q)
    if m:
        h1, mn1, h2, mn2 = int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4))
        delta = (h2 * 60 + mn2) - (h1 * 60 + mn1)
        if delta <= 0:
            delta += 12 * 60  # AM/PM rollover
        return delta
    # Old hourly format: "HAM-H+1AM"
    m = _re2.search(r'(\d{1,2})\s*[ap]m\s*[-–]\s*(\d{1,2})\s*[ap]m', q)
    if m:
        h1, h2 = int(m.group(1)), int(m.group(2))
        delta = (h2 - h1) * 60
        if delta <= 0:
            delta += 12 * 60
        return delta
    return None


class UpDownMomentumStrategy:
    """
    Trades Polymarket "XRP Up or Down - HH:MM-HH:MM" style markets.

    Logic:
      1. Detect the asset from the question.
      2. Measure the 60-second live price momentum from Binance.
      3. If momentum is strongly directional AND the market price for that
         direction is below our fair-value estimate, enter.

    Fair value model:
      - A market priced at 50¢ implies a coin flip.
      - If the asset is up +0.2% in the last 60s, we estimate the chance
        of it being "Up" at resolution is ~65%+ (momentum tends to persist
        over 5-min windows in liquid crypto markets).
      - We enter if market_price < fair_value - MIN_EDGE.
    """

    def __init__(self, min_momentum_pct: float = _MIN_MOMENTUM_PCT) -> None:
        self.min_momentum_pct = min_momentum_pct

    def analyse(self, market: Market, order_book: OrderBook | None) -> TradeSignal | None:
        symbol = _detect_updown_market(market.question)
        if symbol is None:
            return None

        # Warm up the price history on every call (lightweight, cached)
        live_price = _fetch_price(symbol)
        if live_price is None:
            return None

        # Multi-timeframe consensus: combines 30s + 60s + 5m + exchange pressure
        consensus, conf_label = _multitf_consensus(symbol)

        # Require at least MEDIUM confidence — LOW means only marginal cross-TF agreement
        # and fires too easily when price history is sparse.
        if conf_label in ("NONE", "LOW") or abs(consensus) < self.min_momentum_pct:
            m30 = _price_momentum_30s(symbol)
            m60 = _price_momentum_60s(symbol)
            hist_len = len(_PRICE_HISTORY.get(symbol.upper(), []))
            reason = (
                f"warming up — only {hist_len} price ticks so far (need ≥5 over ≥90s)"
                if hist_len < 5
                else f"momentum below threshold (conf={conf_label} consensus={consensus:+.4%})"
            )
            logger.debug(f"[UPDOWN SKIP] {symbol} \"{market.question[:50]}\" — {reason}")
            return None   # insufficient data or too weak

        # Map consensus strength → fair probability
        # Stronger multi-TF agreement → higher fair_prob → larger edge
        raw_confidence = 0.50 + min(abs(consensus) / 0.008, 1.0) * 0.44
        fair_prob = float(np.clip(raw_confidence, 0.52, 0.94))

        # Determine direction from consensus
        if consensus > 0:
            side = "YES"
            token = market.yes_token
            mkt_price = order_book.mid if order_book else market.yes_price
            fair_value = fair_prob
        else:
            side = "NO"
            token = market.no_token
            mkt_price = (1.0 - order_book.mid) if order_book else market.no_price
            fair_value = fair_prob

        fair_value = float(np.clip(fair_value, 0.01, 0.99))
        edge = fair_value - mkt_price

        if edge < config.MIN_EDGE:
            logger.debug(
                f"[UPDOWN SKIP] {symbol} edge={edge:+.3f} < min_edge={config.MIN_EDGE:.3f}  "
                f"fair={fair_value:.3f}  mkt={mkt_price:.3f}  conf={conf_label}"
            )
            return None

        confidence = conf_label  # already set by _multitf_consensus

        direction = "UP" if consensus > 0 else "DOWN"
        m30 = _price_momentum_30s(symbol) or 0.0
        m60 = _price_momentum_60s(symbol) or 0.0
        m5m = _price_momentum_5m(symbol) or 0.0
        pressure = _exchange_pressure(symbol)
        logger.info(
            f"[UPDOWN] {symbol} {direction}  "
            f"30s={m30:+.3%} 60s={m60:+.3%} 5m={m5m:+.3%} press={pressure:+.2f}  "
            f"fair={fair_value:.3f}  mkt={mkt_price:.3f}  edge={edge:+.3f}  "
            f"→ {side} [{confidence}]  \"{market.question[:45]}\""
        )

        # Pass both signals to the learner so it can attribute wins correctly:
        # momentum_signal = multi-TF consensus (price history driven)
        # imbalance_signal = Binance exchange pressure (order book driven)
        return TradeSignal(
            market_id=market.id,
            question=market.question,
            side=side,
            token_id=token.token_id,
            market_price=mkt_price,
            fair_value=fair_value,
            edge=edge,
            signal=float(np.clip(abs(consensus) * 200, 0.0, 1.0)),
            confidence=confidence,
            momentum_signal=float(consensus),
            imbalance_signal=float(pressure),
            is_latency_arb=False,
        )


# ═══════════════════════════════════════════════════════════════════════════
# Strategy 4: BTC Price Level Markets (daily above/below + monthly reach/dip)
# ═══════════════════════════════════════════════════════════════════════════
#
# Modelled on Attentive-Silica ($723K PNL in 1 month, 67% win rate):
#
#  Pattern A — Daily "above $X" safe yield
#    BTC safely above threshold → buy YES at 90-97¢, collect 3-7% edge.
#
#  Pattern B — Monthly/weekly "reach $X" cheap options
#    Buy YES at 0.4-2¢ when true touch probability is 5-30%.
#    Market massively underprices BTC volatility on far-out levels.
#    This is how the +$195K trade (+7,360%) happened.
#
# ═══════════════════════════════════════════════════════════════════════════

import math as _math


def _norm_cdf(z: float) -> float:
    """Fast normal CDF (Abramowitz & Stegun)."""
    if z >= 8.0:  return 1.0
    if z <= -8.0: return 0.0
    t = 1.0 / (1.0 + 0.2316419 * abs(z))
    d = 0.3989423 * _math.exp(-z * z / 2.0)
    p = d * t * (0.3193815 + t * (-0.3565638 + t * (1.7814779 + t * (-1.8212560 + t * 1.3302744))))
    return (1.0 - p) if z >= 0 else p


def _prob_above(current: float, threshold: float, days: float, daily_vol: float = 0.04) -> float:
    """P(log-normal price ends above threshold after `days` days)."""
    if days <= 0:
        return 1.0 if current >= threshold else 0.0
    vol = daily_vol * _math.sqrt(days)
    z   = _math.log(current / threshold) / vol
    return _norm_cdf(z)


def _prob_touch(current: float, target: float, days: float, daily_vol: float = 0.04) -> float:
    """
    P(price touches `target` at any point over `days` days).
    Reflection principle: P(touch) = 2 * N(-|log(current/target)| / vol).
    """
    if days <= 0:
        return 0.0
    vol      = daily_vol * _math.sqrt(days)
    log_dist = abs(_math.log(current / target))
    return min(2.0 * _norm_cdf(-log_dist / vol), 0.999)


def _parse_btc_level(question: str):
    """
    Parse a BTC price-level question.
    Returns (mtype, p1, p2) or None.
    mtype: 'above' | 'below' | 'between' | 'reach' | 'dip'
    """
    q = question.lower()
    if "bitcoin" not in q and "btc" not in q:
        return None

    def _px(s: str) -> float | None:
        s = s.replace(",", "").strip()
        m = _re.match(r"(\d+(?:\.\d+)?)([kmb]?)", s)
        if not m:
            return None
        v   = float(m.group(1))
        mul = {"k": 1_000, "m": 1_000_000, "b": 1_000_000_000}.get(m.group(2), 1)
        return v * mul

    for pat, mtype in (
        (r"(?:be\s+)?(?:above|greater\s+than)\s+\$?([\d,]+(?:\.\d+)?)", "above"),
        (r"(?:be\s+)?(?:less\s+than|below)\s+\$?([\d,]+(?:\.\d+)?)",    "below"),
        (r"reach\s+\$?([\d,]+(?:\.\d+)?)",                               "reach"),
        (r"dip\s+to\s+\$?([\d,]+(?:\.\d+)?)",                            "dip"),
    ):
        m = _re.search(pat, q)
        if m:
            p = _px(m.group(1))
            return (mtype, p, None) if p else None

    m = _re.search(r"between\s+\$?([\d,]+)\s+and\s+\$?([\d,]+)", q)
    if m:
        p1, p2 = _px(m.group(1)), _px(m.group(2))
        return ("between", p1, p2) if p1 and p2 else None

    return None


class BTCLevelStrategy:
    """
    Trades BTC daily/weekly/monthly price level markets.

    Four sub-patterns run simultaneously:

    A) Daily above/below  — safe yield when BTC is far from threshold.
    B) Weekly above/below — moderate certainty, multi-day window.
    C) Reach/dip cheap options — buy YES at <5¢ when fair prob is 3×+
       the market price. The +$195K trade was this pattern.
    D) Range (between) — buy NO when BTC is far outside the range.
    """

    _DAILY_VOL             = 0.04   # 4% daily BTC vol (conservative)
    _MIN_CHEAP_RATIO       = 3.0    # fair / market must be >= 3× for cheap options
    _CHEAP_OPTION_MAX_PRICE = 0.05  # only pattern C when market price <= 5¢

    def analyse(self, market: Market, order_book: OrderBook | None) -> TradeSignal | None:
        parsed = _parse_btc_level(market.question)
        if parsed is None:
            return None

        mtype, p1, p2 = parsed
        current_btc = _fetch_price("BTC")
        if not current_btc or not p1:
            return None

        # Days to resolution
        days = 1.0
        if market.end_date:
            try:
                from datetime import datetime, timezone as _tz
                end  = datetime.fromisoformat(market.end_date.replace("Z", "+00:00"))
                days = max(0.05, (end - datetime.now(_tz.utc)).total_seconds() / 86400)
            except Exception:
                pass

        mkt_yes = order_book.mid if order_book else market.yes_price
        mkt_no  = 1.0 - mkt_yes

        # ── Fair probabilities ────────────────────────────────────────────
        if mtype == "above":
            fair_yes = _prob_above(current_btc, p1, days, self._DAILY_VOL)
        elif mtype == "below":
            fair_yes = 1.0 - _prob_above(current_btc, p1, days, self._DAILY_VOL)
        elif mtype in ("reach", "dip"):
            fair_yes = _prob_touch(current_btc, p1, days, self._DAILY_VOL)
        elif mtype == "between":
            fair_yes = (_prob_above(current_btc, p1, days, self._DAILY_VOL)
                        - _prob_above(current_btc, p2, days, self._DAILY_VOL))
        else:
            return None

        fair_yes = float(np.clip(fair_yes, 0.001, 0.999))
        fair_no  = 1.0 - fair_yes
        edge_yes = fair_yes - mkt_yes
        edge_no  = fair_no  - mkt_no

        # ── Pattern C: cheap touch options ────────────────────────────────
        if mtype in ("reach", "dip") and mkt_yes <= self._CHEAP_OPTION_MAX_PRICE:
            ratio = fair_yes / max(mkt_yes, 0.001)
            if ratio >= self._MIN_CHEAP_RATIO:
                confidence = "HIGH" if ratio >= 8 else "MEDIUM" if ratio >= 5 else "LOW"
                logger.info(
                    f"[BTC-LEVEL CHEAP] {mtype.upper()} ${p1:,.0f}  BTC=${current_btc:,.0f}  "
                    f"fair={fair_yes:.3f}  mkt={mkt_yes:.4f}  ratio={ratio:.1f}×  days={days:.0f}  "
                    f"→ YES [{confidence}]  \"{market.question[:50]}\""
                )
                return TradeSignal(
                    market_id=market.id,
                    question=market.question,
                    side="YES",
                    token_id=market.yes_token.token_id,
                    market_price=mkt_yes,
                    fair_value=fair_yes,
                    edge=fair_yes - mkt_yes,
                    signal=fair_yes - mkt_yes,
                    confidence=confidence,
                    is_latency_arb=False,
                )

        # ── Patterns A/B/D: standard edge threshold ───────────────────────
        if edge_yes >= edge_no and edge_yes > config.MIN_EDGE:
            side, token, mkt_p, fair_p, edge = "YES", market.yes_token, mkt_yes, fair_yes, edge_yes
        elif edge_no > config.MIN_EDGE:
            side, token, mkt_p, fair_p, edge = "NO",  market.no_token,  mkt_no,  fair_no,  edge_no
        else:
            return None

        confidence = "HIGH" if edge > 0.15 else "MEDIUM" if edge > 0.08 else "LOW"
        logger.info(
            f"[BTC-LEVEL] {mtype.upper()} ${p1:,.0f}  BTC=${current_btc:,.0f}  "
            f"fair={fair_p:.3f}  mkt={mkt_p:.3f}  edge={edge:+.3f}  days={days:.1f}  "
            f"→ {side} [{confidence}]  \"{market.question[:50]}\""
        )
        return TradeSignal(
            market_id=market.id,
            question=market.question,
            side=side,
            token_id=token.token_id,
            market_price=mkt_p,
            fair_value=fair_p,
            edge=edge,
            signal=edge,
            confidence=confidence,
            is_latency_arb=False,
        )


# ═══════════════════════════════════════════════════════════════════════════
# Strategy 5: Live Sports Settlement Lag  (kch123 pattern)
# ═══════════════════════════════════════════════════════════════════════════
#
# kch123 turned $340 → $10M+ by exploiting Polymarket's live sports markets.
# His Super Bowl edge: $1.8M in one day on Seahawks spreads.
#
# The pattern: Polymarket's oracle updates with a delay during live games.
# If a team scores making the outcome ~95% certain, the market still shows
# 50-60¢ for 30-120 seconds. That's a massive edge.
#
# This strategy uses ESPN's free public API for live scores + win probability,
# then finds the matching Polymarket market and trades the discrepancy.
#
# No API key needed — ESPN data is publicly accessible.
# ═══════════════════════════════════════════════════════════════════════════

_SPORTS_PRICE_CACHE: dict[str, tuple[dict, float]] = {}
_SPORTS_CACHE_TTL = 15.0   # refresh live scores every 15s


def _fetch_live_sports() -> list[dict]:
    """
    Fetch live game scores + win probabilities from ESPN's public API.
    Returns list of {home, away, home_score, away_score, home_win_prob,
    status, sport, league}.
    """
    endpoints = [
        ("nfl",  "americanfootball_nfl",  "https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard"),
        ("nba",  "basketball_nba",        "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/scoreboard"),
        ("mlb",  "baseball_mlb",          "https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard"),
        ("nhl",  "hockey_nhl",            "https://site.api.espn.com/apis/site/v2/sports/hockey/nhl/scoreboard"),
        ("soccer_epl", "soccer",          "https://site.api.espn.com/apis/site/v2/sports/soccer/eng.1/scoreboard"),
    ]
    games = []
    now = time.time()

    for sport, league, url in endpoints:
        cached = _SPORTS_PRICE_CACHE.get(sport)
        if cached and (now - cached[1]) < _SPORTS_CACHE_TTL:
            games.extend(cached[0].get("games", []))
            continue
        try:
            resp = requests.get(url, timeout=5)
            if resp.status_code != 200:
                continue
            data = resp.json()
            sport_games = []
            for event in data.get("events", []):
                comp = event.get("competitions", [{}])[0]
                status = comp.get("status", {}).get("type", {})
                if not status.get("inProgress", False):
                    continue   # only care about LIVE games
                competitors = comp.get("competitors", [])
                if len(competitors) < 2:
                    continue
                home = next((c for c in competitors if c.get("homeAway") == "home"), competitors[0])
                away = next((c for c in competitors if c.get("homeAway") == "away"), competitors[1])

                # Win probability from ESPN (available for NFL/NBA/MLB)
                home_win_prob = 0.5
                for pred in comp.get("predictor", {}).get("homeTeam", {}).get("statistics", []):
                    if pred.get("name") == "winPercentage":
                        home_win_prob = float(pred.get("displayValue", "50").replace("%", "")) / 100
                        break

                # Fallback: infer from score + time remaining
                clock = status.get("detail", "")
                home_score = int(home.get("score", 0) or 0)
                away_score = int(away.get("score", 0) or 0)

                g = {
                    "sport":         sport,
                    "home":          home.get("team", {}).get("displayName", ""),
                    "away":          away.get("team", {}).get("displayName", ""),
                    "home_abbr":     home.get("team", {}).get("abbreviation", ""),
                    "away_abbr":     away.get("team", {}).get("abbreviation", ""),
                    "home_score":    home_score,
                    "away_score":    away_score,
                    "home_win_prob": home_win_prob,
                    "clock":         clock,
                    "period":        status.get("period", 0),
                }
                sport_games.append(g)
                games.append(g)
            _SPORTS_PRICE_CACHE[sport] = ({"games": sport_games}, now)
        except Exception:
            pass
    return games


def _match_sports_market(market_question: str, live_games: list[dict]) -> dict | None:
    """
    Fuzzy-match a Polymarket market question to a live game.
    Returns the live game dict if matched, else None.
    """
    q = market_question.lower()
    for game in live_games:
        home = game["home"].lower()
        away = game["away"].lower()
        home_abbr = game["home_abbr"].lower()
        away_abbr = game["away_abbr"].lower()
        # Match if both team names (or abbreviations) appear in the question
        home_match = any(part in q for part in [home, home_abbr, home.split()[-1]])
        away_match = any(part in q for part in [away, away_abbr, away.split()[-1]])
        if home_match and away_match:
            return game
    return None


class SportsLiveStrategy:
    """
    Exploits Polymarket's live sports market settlement lag.

    The kch123 pattern: during a live game, Polymarket's oracle updates
    slowly. When a team is effectively certain to win but the market
    still shows 50-60¢, that's a 30-40¢ free edge.

    Uses ESPN's public API for real-time win probability.
    No API key required.

    Edge threshold: only fires when ESPN win_prob vs market_price
    diverges by more than MIN_SPORTS_EDGE (default 15%).
    """

    MIN_SPORTS_EDGE = 0.15   # minimum edge to trade

    def analyse(self, market: Market, order_book: OrderBook | None) -> TradeSignal | None:
        live_games = _fetch_live_sports()
        if not live_games:
            return None

        game = _match_sports_market(market.question, live_games)
        if game is None:
            return None

        home_win_prob = game["home_win_prob"]
        away_win_prob = 1.0 - home_win_prob

        mkt_yes = order_book.mid if order_book else market.yes_price

        # Determine which team the YES outcome represents
        q = market.question.lower()
        home_name = game["home"].lower().split()[-1]
        home_is_yes = home_name in q

        if home_is_yes:
            fair_yes = home_win_prob
        else:
            fair_yes = away_win_prob

        fair_no  = 1.0 - fair_yes
        mkt_no   = 1.0 - mkt_yes
        edge_yes = fair_yes - mkt_yes
        edge_no  = fair_no  - mkt_no

        if edge_yes >= edge_no and edge_yes >= self.MIN_SPORTS_EDGE:
            side, token, mkt_p, fair_p, edge = "YES", market.yes_token, mkt_yes, fair_yes, edge_yes
        elif edge_no >= self.MIN_SPORTS_EDGE:
            side, token, mkt_p, fair_p, edge = "NO",  market.no_token,  mkt_no,  fair_no,  edge_no
        else:
            return None

        confidence = "HIGH" if edge > 0.30 else "MEDIUM" if edge > 0.20 else "LOW"
        logger.info(
            f"[SPORTS-LIVE] {game['away_abbr']} {game['away_score']} @ "
            f"{game['home_abbr']} {game['home_score']}  {game['clock']}  "
            f"ESPN_win={fair_yes:.2f}  mkt={mkt_p:.2f}  edge={edge:+.2f}  "
            f"→ {side} [{confidence}]  \"{market.question[:50]}\""
        )
        return TradeSignal(
            market_id=market.id,
            question=market.question,
            side=side,
            token_id=token.token_id,
            market_price=mkt_p,
            fair_value=fair_p,
            edge=edge,
            signal=edge,
            confidence=confidence,
            is_latency_arb=False,  # use Kelly sizing, not fixed arb budget
        )


# ═══════════════════════════════════════════════════════════════════════════
# Strategy 6: Sudden Price Move Detection (news/event arb)
# ═══════════════════════════════════════════════════════════════════════════
#
# When news breaks, Polymarket prices move fast but not instantly.
# If a market's YES price jumped >15% since last loop, someone knows something.
# We follow the move assuming it continues for at least 1-2 more loops.
# ═══════════════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════════════
# Strategy 7: Sports Spread Arbitrage vs. Vegas Consensus  (kch123 pattern)
# ═══════════════════════════════════════════════════════════════════════════
#
# kch123's actual edge: Polymarket sports spread odds are frequently mispriced
# vs. the consensus line from traditional sportsbooks (DraftKings, FanDuel…).
#
# He places 14,303 directional YES buys — zero sells — and holds to resolution.
# $11.15M profit, 61% win rate, ~$1.8M on Super Bowl Seahawks spreads alone.
#
# This strategy:
#   1. Polls The Odds API (free tier: 500 req/month) for live bookmaker lines
#   2. Converts bookmaker odds → consensus probability
#   3. Fuzzy-matches Polymarket market question → game
#   4. Fires when Polymarket's implied prob diverges from Vegas by ≥ MIN_EDGE
#
# Set ODDS_API_KEY in .env to enable.  Without it, strategy silently skips.
# Free key at: https://the-odds-api.com  (takes 30 seconds to register)
# ═══════════════════════════════════════════════════════════════════════════

_ODDS_CACHE: dict[str, tuple[list, float]] = {}   # sport_key → (games, fetched_at)
_ODDS_CACHE_TTL = 60.0   # seconds — conservative to preserve free-tier quota

_ODDS_SPORTS = [
    ("americanfootball_nfl",          "nfl"),
    ("basketball_nba",                "nba"),
    ("baseball_mlb",                  "mlb"),
    ("icehockey_nhl",                 "nhl"),
    ("soccer_epl",                    "epl"),
    ("soccer_uefa_champs_league",     "ucl"),
    ("soccer_usa_mls",                "mls"),
]


def _fetch_vegas_odds() -> list[dict]:
    """
    Fetch upcoming/live odds from The Odds API.
    Returns list of normalised game dicts:
      {sport, home_team, away_team, home_prob, away_prob, commence_time}
    """
    api_key = config.ODDS_API_KEY
    if not api_key:
        return []

    all_games: list[dict] = []
    now = time.time()

    for sport_key, label in _ODDS_SPORTS:
        cached = _ODDS_CACHE.get(sport_key)
        if cached and (now - cached[1]) < _ODDS_CACHE_TTL:
            all_games.extend(cached[0])
            continue

        try:
            resp = requests.get(
                f"https://api.the-odds-api.com/v4/sports/{sport_key}/odds/",
                params={
                    "apiKey":      api_key,
                    "regions":     "us",
                    "markets":     "h2h",
                    "oddsFormat":  "decimal",
                    "dateFormat":  "iso",
                },
                timeout=8,
            )
            if resp.status_code == 401:
                logger.warning("[ODDS-API] Invalid API key — sports spread arb disabled")
                _ODDS_CACHE[sport_key] = ([], now)
                continue
            if resp.status_code == 422:
                # Sport not currently in season
                _ODDS_CACHE[sport_key] = ([], now)
                continue
            if resp.status_code != 200:
                continue
            events = resp.json()
            sport_games: list[dict] = []
            for ev in events:
                home = ev.get("home_team", "")
                away = ev.get("away_team", "")
                bookmakers = ev.get("bookmakers", [])
                if not bookmakers:
                    continue

                # Collect h2h prices from all bookmakers, average them
                home_probs, away_probs = [], []
                for bm in bookmakers:
                    for mkt in bm.get("markets", []):
                        if mkt.get("key") != "h2h":
                            continue
                        for outcome in mkt.get("outcomes", []):
                            price = float(outcome.get("price", 0))
                            if price <= 1:
                                continue
                            prob = 1.0 / price
                            if outcome.get("name") == home:
                                home_probs.append(prob)
                            elif outcome.get("name") == away:
                                away_probs.append(prob)

                if not home_probs or not away_probs:
                    continue

                # Consensus probability (average, then normalise to sum=1)
                raw_home = sum(home_probs) / len(home_probs)
                raw_away = sum(away_probs) / len(away_probs)
                total    = raw_home + raw_away
                home_prob = raw_home / total
                away_prob = raw_away / total

                g = {
                    "sport":          label,
                    "home_team":      home,
                    "away_team":      away,
                    "home_prob":      home_prob,
                    "away_prob":      away_prob,
                    "commence_time":  ev.get("commence_time", ""),
                }
                sport_games.append(g)
                all_games.append(g)

            remaining = resp.headers.get("x-requests-remaining", "?")
            logger.debug(f"[ODDS-API] {label}: {len(sport_games)} games  quota_remaining={remaining}")
            _ODDS_CACHE[sport_key] = (sport_games, now)

        except Exception as exc:
            logger.debug(f"[ODDS-API] {sport_key} fetch failed: {exc}")

    return all_games


_GENERIC_SPORT_WORDS = frozenset({
    # Common English words that appear in many team names
    "city", "united", "real", "club", "town", "county", "athletic",
    "sport", "sports", "football", "soccer", "basketball", "baseball",
    "hockey", "league", "national", "american", "international",
    "north", "south", "east", "west", "central", "royal", "red", "blue",
    "black", "white", "green", "gold", "silver", "state", "metro",
    "college", "university",
})

# Map Odds-API sport keys to keywords that should appear in the question
_SPORT_QUESTION_HINTS: dict[str, tuple[str, ...]] = {
    "basketball_nba":         ("nba", "basketball"),
    "americanfootball_nfl":   ("nfl", "super bowl", "football"),
    "baseball_mlb":           ("mlb", "baseball", "world series"),
    "icehockey_nhl":          ("nhl", "hockey", "stanley cup"),
    "soccer_epl":             ("premier league", "epl", "soccer", "football"),
    "soccer_mls":             ("mls", "major league soccer", "soccer"),
    "soccer_uefa_champs_league": ("champions league", "ucl", "soccer"),
}


def _match_vegas_game(market_question: str, games: list[dict]) -> dict | None:
    """
    Fuzzy-match a Polymarket question to a Vegas game.
    Returns the game dict only when we have high confidence:
      - At least 2 meaningful (non-generic) words from each team must appear
        in the question, OR the full team name substring is present.
      - The sport type must be consistent with the question wording.
    """
    q = market_question.lower()
    best: dict | None = None
    best_score = 0

    for game in games:
        sport_key = game.get("sport_key", "")
        home_team = game["home_team"]
        away_team = game["away_team"]

        home_lower = home_team.lower()
        away_lower = away_team.lower()

        # Fast path: exact substring match for either team
        home_exact = home_lower in q
        away_exact = away_lower in q

        if home_exact or away_exact:
            score = 10 + int(home_exact) + int(away_exact)
        else:
            # Count non-generic meaningful words per team
            home_parts = [w for w in home_lower.split() if w not in _GENERIC_SPORT_WORDS and len(w) >= 3]
            away_parts = [w for w in away_lower.split() if w not in _GENERIC_SPORT_WORDS and len(w) >= 3]

            home_hits = sum(1 for w in home_parts if w in q)
            away_hits = sum(1 for w in away_parts if w in q)

            # Need ≥1 meaningful hit from EACH team to avoid cross-sport matches
            if home_hits == 0 or away_hits == 0:
                continue

            # At least 2 total meaningful hits to reduce false positives
            score = home_hits + away_hits
            if score < 2:
                continue

        # Sport-type consistency check: if we know the sport, the question
        # should contain at least one hint word for that sport.
        hints = _SPORT_QUESTION_HINTS.get(sport_key)
        if hints and not any(h in q for h in hints):
            continue

        if score > best_score:
            best_score = score
            best = game

    return best


class SportsSpreadArbStrategy:
    """
    Compares Polymarket sports market implied probabilities against the
    Vegas consensus line from The Odds API.

    When Polymarket prices a team at 0.45 but Vegas consensus says 0.62,
    the expected value of buying YES is enormous — this is the kch123 edge.

    Requires ODDS_API_KEY in .env (free tier: 500 req/month).
    Without a key this strategy is silently skipped.

    MIN_EDGE: minimum divergence to trade (default 5¢ / 5%)
    """

    MIN_EDGE = config.MIN_EDGE   # use global config (default 3%)

    # Championship / season-title keywords — these markets resolve over months
    # and should NOT be compared against single-game Vegas moneylines.
    _CHAMPIONSHIP_PHRASES = (
        "stanley cup", "nba finals", "nba championship",
        "super bowl", "world series", "nfl championship",
        "champions league", "premier league winner",
        "mls cup", "nhl champion",
        "win the 2026", "win the 2025",   # catches most futures
        "win the championship", "win the title",
    )

    def analyse(self, market: Market, order_book: OrderBook | None) -> TradeSignal | None:
        # Skip championship/futures markets — they can't be compared to
        # single-game Vegas moneylines (apples vs oranges).
        q_lower = market.question.lower()
        if any(phrase in q_lower for phrase in self._CHAMPIONSHIP_PHRASES):
            return None

        games = _fetch_vegas_odds()
        if not games:
            return None

        game = _match_vegas_game(market.question, games)
        if game is None:
            return None

        # Order book must show real liquidity — mid=0.5 on empty book is not
        # a real market price and would generate fake edge vs Vegas.
        if order_book is None or (order_book.best_bid == 0.0 and order_book.best_ask == 1.0):
            return None   # no real quotes, skip

        mkt_yes = order_book.mid
        mkt_no  = 1.0 - mkt_yes

        # Determine which team the YES outcome maps to
        q = market.question.lower()
        home_parts = game["home_team"].lower().split()
        away_parts = game["away_team"].lower().split()

        home_in_q = any(len(w) >= 4 and w in q for w in home_parts)
        away_in_q = any(len(w) >= 4 and w in q for w in away_parts)

        # Prefer the team whose name appears nearest "win" in the question
        # Fallback: home team = YES if home is mentioned first
        home_pos = min((q.find(w) for w in home_parts if len(w) >= 4 and w in q), default=9999)
        away_pos = min((q.find(w) for w in away_parts if len(w) >= 4 and w in q), default=9999)

        if home_in_q and (not away_in_q or home_pos <= away_pos):
            fair_yes = game["home_prob"]
            team_label = game["home_team"]
        elif away_in_q:
            fair_yes = game["away_prob"]
            team_label = game["away_team"]
        else:
            return None

        fair_no  = 1.0 - fair_yes
        edge_yes = fair_yes - mkt_yes
        edge_no  = fair_no  - mkt_no

        if edge_yes >= edge_no and edge_yes >= self.MIN_EDGE:
            side, token, mkt_p, fair_p, edge = "YES", market.yes_token, mkt_yes, fair_yes, edge_yes
        elif edge_no >= self.MIN_EDGE:
            side, token, mkt_p, fair_p, edge = "NO",  market.no_token,  mkt_no,  fair_no,  edge_no
        else:
            return None

        confidence = "HIGH" if edge > 0.15 else "MEDIUM" if edge > 0.08 else "LOW"
        logger.info(
            f"[SPORTS-SPREAD-ARB] {game['away_team']} @ {game['home_team']}  "
            f"Vegas={fair_yes:.3f}  Poly={mkt_yes:.3f}  edge={edge:+.3f}  "
            f"→ {side} on {team_label} [{confidence}]  \"{market.question[:50]}\""
        )
        return TradeSignal(
            market_id=market.id,
            question=market.question,
            side=side,
            token_id=token.token_id,
            market_price=mkt_p,
            fair_value=fair_p,
            edge=edge,
            signal=edge,
            confidence=confidence,
            is_latency_arb=False,  # use Kelly sizing, not fixed arb budget
        )


_PREV_PRICES: dict[str, float] = {}   # market_id → last YES price

# ═══════════════════════════════════════════════════════════════════════════
# Strategy 8: News Arbitrage  (headline sentiment vs market price)
# ═══════════════════════════════════════════════════════════════════════════
#
# When a relevant news headline breaks, Polymarket markets may not have
# repriced yet.  This strategy:
#   1. Looks up recent headlines (24h memory) relevant to the market question.
#   2. Computes aggregate sentiment from those headlines.
#   3. If sentiment strongly disagrees with the current market price, enters.
#
# Example: "Fed cuts rates unexpectedly" → sentiment +1 for BTC markets
#   BTC market still priced at 0.45 → big edge to buy YES.
#
# Uses the news_learner (separate AdaptiveLearner) so news trades don't
# pollute momentum/imbalance strategy statistics.
# ═══════════════════════════════════════════════════════════════════════════


def update_price_snapshot(market_id: str, yes_price: float) -> None:
    _PREV_PRICES[market_id] = yes_price


class NewsEventStrategy:
    """
    Momentum follow on sudden market price moves.

    If a market's YES price moved ≥ JUMP_THRESHOLD since last scan,
    follow the direction — the move likely reflects breaking news that
    hasn't fully propagated through the market yet.

    This is the "Trump tariff announcement" pattern: market goes from
    40¢ to 75¢ in one loop. We catch the remaining 25¢ move.
    """

    JUMP_THRESHOLD = 0.12   # 12% sudden move triggers the signal
    MIN_EDGE       = 0.08   # minimum remaining edge after the jump

    def analyse(self, market: Market, order_book: OrderBook | None) -> TradeSignal | None:
        prev = _PREV_PRICES.get(market.id)
        current = order_book.mid if order_book else market.yes_price
        update_price_snapshot(market.id, current)

        if prev is None:
            return None   # first time seeing this market

        move = current - prev
        if abs(move) < self.JUMP_THRESHOLD:
            return None

        # Follow the move direction
        if move > 0:
            # YES jumped — buy YES (momentum continuation)
            fair_yes = min(current + move * 0.5, 0.97)   # extrapolate 50% more
            edge = fair_yes - current
            if edge < self.MIN_EDGE:
                return None
            side, token, mkt_p, fair_p = "YES", market.yes_token, current, fair_yes
        else:
            # YES dumped — buy NO
            fair_no  = min((1 - current) + abs(move) * 0.5, 0.97)
            mkt_no   = 1.0 - current
            edge     = fair_no - mkt_no
            if edge < self.MIN_EDGE:
                return None
            side, token, mkt_p, fair_p = "NO", market.no_token, mkt_no, fair_no

        confidence = "HIGH" if abs(move) > 0.25 else "MEDIUM"
        logger.info(
            f"[NEWS-EVENT] {market.question[:55]}  "
            f"prev={prev:.3f}  now={current:.3f}  move={move:+.3f}  "
            f"→ {side} [{confidence}]"
        )
        return TradeSignal(
            market_id=market.id,
            question=market.question,
            side=side,
            token_id=token.token_id,
            market_price=mkt_p,
            fair_value=fair_p,
            edge=edge,
            signal=move,
            confidence=confidence,
            is_latency_arb=False,  # use Kelly sizing
        )


class NewsArbitrageStrategy:
    """
    Trades markets where recent news headlines strongly disagree with the
    current market price.

    Algorithm:
      1. Fetch up to MAX_HEADLINES recent headlines relevant to this market
         from the NewsFeed 24h memory.
      2. Average their sentiment scores (−1 = bearish, +1 = bullish).
      3. Compute an implied "should-be" probability from sentiment:
           avg_sentiment ≥ +MIN_SENTIMENT → fair_yes ≈ 0.65–0.85
           avg_sentiment ≤ −MIN_SENTIMENT → fair_no ≈ 0.65–0.85
      4. Enter when edge > MIN_EDGE.

    Trades are tagged is_news_arb=True so they go through the separate
    news AdaptiveLearner and count against the daily news trade cap.
    """

    MIN_SENTIMENT  = 0.20   # minimum absolute avg sentiment to act
    MIN_EDGE       = 0.08   # minimum edge after fair-value estimate
    MIN_RELEVANCE  = 0.20   # minimum news score against market question
    MAX_HEADLINES  = 5      # use top-5 most relevant headlines

    def __init__(self, news_feed) -> None:
        """news_feed: a NewsFeed instance (imported lazily to avoid circular dep)."""
        self._feed = news_feed

    def analyse(self, market: Market, order_book: OrderBook | None) -> TradeSignal | None:
        try:
            headlines = self._feed.recent_for_market(
                market.question,
                max_results=self.MAX_HEADLINES,
                min_score=self.MIN_RELEVANCE,
            )
            if not headlines:
                return None

            sentiments = [h.sentiment for h in headlines]
            avg_sent   = sum(sentiments) / len(sentiments)

            if abs(avg_sent) < self.MIN_SENTIMENT:
                return None   # too weak or mixed

            mkt_yes = order_book.mid if order_book else market.yes_price
            mkt_no  = 1.0 - mkt_yes

            # Map sentiment magnitude to fair probability (0.65 at MIN, 0.85 at ±1.0)
            strength  = min(abs(avg_sent), 1.0)
            fair_prob = 0.50 + strength * 0.35   # 0.50 → 0.85

            if avg_sent > 0:
                # Bullish headlines → favour YES
                fair_yes  = float(np.clip(fair_prob, 0.01, 0.99))
                fair_no   = 1.0 - fair_yes
                edge_yes  = fair_yes - mkt_yes
                edge_no   = fair_no  - mkt_no
                if edge_yes >= edge_no and edge_yes >= self.MIN_EDGE:
                    side, token, mkt_p, fair_p, edge = "YES", market.yes_token, mkt_yes, fair_yes, edge_yes
                elif edge_no >= self.MIN_EDGE:
                    side, token, mkt_p, fair_p, edge = "NO",  market.no_token,  mkt_no,  fair_no,  edge_no
                else:
                    return None
            else:
                # Bearish headlines → favour NO
                fair_no   = float(np.clip(fair_prob, 0.01, 0.99))
                fair_yes  = 1.0 - fair_no
                edge_yes  = fair_yes - mkt_yes
                edge_no   = fair_no  - mkt_no
                if edge_no >= edge_yes and edge_no >= self.MIN_EDGE:
                    side, token, mkt_p, fair_p, edge = "NO",  market.no_token,  mkt_no,  fair_no,  edge_no
                elif edge_yes >= self.MIN_EDGE:
                    side, token, mkt_p, fair_p, edge = "YES", market.yes_token, mkt_yes, fair_yes, edge_yes
                else:
                    return None

            confidence = "HIGH" if abs(avg_sent) > 0.6 else "MEDIUM" if abs(avg_sent) > 0.35 else "LOW"

            top = headlines[0].title[:50]
            logger.info(
                f"[NEWS-ARB] \"{market.question[:55]}\"  "
                f"headlines={len(headlines)}  avg_sent={avg_sent:+.2f}  "
                f"fair={fair_p:.3f}  mkt={mkt_p:.3f}  edge={edge:+.3f}  "
                f"→ {side} [{confidence}]  top: \"{top}\""
            )

            return TradeSignal(
                market_id=market.id,
                question=market.question,
                side=side,
                token_id=token.token_id,
                market_price=mkt_p,
                fair_value=fair_p,
                edge=edge,
                signal=avg_sent,
                confidence=confidence,
                momentum_signal=0.0,
                imbalance_signal=avg_sent,
                is_latency_arb=False,
                is_news_arb=True,
            )

        except Exception as exc:
            logger.warning(f"[NEWS-ARB] Error on {market.id}: {exc}")
            return None
